### ISSUE TITLE
media-video/lightworks: Low performance and may have some license issue

### ISSUE THREAD

**Issue by HougeLangley** [gentoo-zh/overlay#1004]
From now on this App update to many version. But got bad performance. 

The license of this App may have some issue.

Please Drop
![2021-06-11_12-18](https://user-images.githubusercontent.com/1161594/121630217-52130d80-caaf-11eb-9641-933be1ecba78.png)

**Comment by aieu** [comment]
https://github.com/microcai/gentoo-zh/pull/1006
