### ISSUE TITLE
app-i18n/fcitx5: Target "classicui" links to target "PkgConfig::GdkPixbuf" but the target   was not found

### ISSUE THREAD

**Issue by liangyongxiang** [gentoo-zh/overlay#1040]
test fcitx5 in stage3:
```
emerge -v --autounmask=y --autounmask-continue=y --autounmask-write fcitx5
```

http://fars.ee/LEWq

**Comment by wgjak47** [comment]
```
https://packages.gentoo.org/packages/x11-libs/gdk-pixbuf
```

looks like missing this package. the fcitx5 is build on desktop profile. I think there is more packages missing in pure stage3 environment.

**Comment by liangyongxiang** [comment]
所以我们需要补全？ 还是在readme或者其他地方提醒用户？

**Comment by aieu** [comment]
需要补全依赖
https://github.com/fcitx/fcitx5/blob/master/CMakeLists.txt#L149-L154
