### ISSUE TITLE
Is it necessary to add a new package: `app-i18n/fcitx5-meta` ?

### ISSUE THREAD

**Issue by bekcpear** [gentoo-zh/overlay#1045]
At the present, when installing `app-i18n/fcitx5`, `app-i18n/fcitx5-qt` and `app-i18n/fcitx5-gtk` will not be dependent, even if qt5 and gtk2/3 are enabled under the global USE. 

However, if anybody want to use fcitx5 on gtk2/3 or qt5 programs, these two packages must be installed, which leads to manual installation, which I think is unreasonable.

So, I think the `app-i18n/fcitx5-meta` is necessary.

This is the dependency tree for `app-i18n/fcitx5-meta` I preferred:
```
app-i18n/fcitx5-meta
 ` --               app-i18n/fcitx5
 ` -- [+qt5]        app-i18n/fcitx5-qt[qt5]
 ` -- [+gtk2]       app-i18n/fcitx5-gtk[gtk2]
 ` -- [+gtk3]       app-i18n/fcitx5-gtk[gtk3]
 ` -- [configtool]  app-i18n/fcitx5-configtool
```

and `app-i18n/fcitx5-rime` or `app-i18n/fcitx5-skk` will depending on
```
app-i18n/fcitx5-meta (default)
  OR
app-i18n/fcitx5 
```

<s>A question is the choice of version number for this meta package(and when bump), the version of fcitx5-* packages is not consistent.</s> The largest version of fcitx5-* packages will be okay I think.

**Comment by jian-lin** [comment]
According to the [devmanual](https://devmanual.gentoo.org/general-concepts/use-flags/index.html#when-not-to-use-use-flags), what about telling users to install `fcitx5-qt` and `fcitx5-gtk` in the post install messages of `fcitx5`.

Here is an example.

```bash
inherit optfeature
pkg_postinst() {
    optfeature "qt support" "app-i18n/fcitx5-qt"
    optfeature "gtk support" "app-i18n/fcitx5-gtk"
}
```

**Comment by bekcpear** [comment]
@jian-lin This is a meta package, similar to `kde-plasma/plasma-meta`

There are some reasons I want to add it:

- the input is the core function for fcitx5, if the qt5/gtk2/gtk3 USE enabled globally, the corresponding programs is installed on the system implicitly.
- e-log messages is easy to be ignored
- this package will make the `@world` set neater (a `app-i18n/fcitx5-rime` record is enough for Chinese input)

**Comment by jian-lin** [comment]
I agree with your first and last points and agree to add the meta package.
However, if someone has trouble because they ignore elog messages, they get what they deserve.
