### ISSUE TITLE
app-office/wps-office: Unresolved soname dependencies

### ISSUE THREAD

**Issue by resolut1on2021** [gentoo-zh/overlay#1128]
After something wrong , app-office/wps-office didn't work any more.
I  opened it through terminal , but no error message accured.
When I reinstalled wps , it seemed that Unresolved soname dependencies error like this:
`
QA Notice: Unresolved soname dependencies:  
/opt/kingsoft/wps-office/office6/librpcetapi.so: libQtXml.so.4
/opt/kingsoft/wps-office/office6/librpcetapi_sysqt5.so: libQt5Core.so.5 libQt5Gui.so.5 libQt5Network.so.5 libQt5Widgets.so.5 libQt5Xml.so.5
/opt/kingsoft/wps-office/office6/librpcwppapi.so: libQtXml.so.4
/opt/kingsoft/wps-office/office6/librpcwppapi_sysqt5.so: libQt5Core.so.5 libQt5Gui.so.5 libQt5Network.so.5 libQt5Widgets.so.5 libQt5Xml.so.5
/opt/kingsoft/wps-office/office6/librpcwpsapi.so: libQtXml.so.4
/opt/kingsoft/wps-office/office6/librpcwpsapi_sysqt5.so: libQt5Core.so.5 libQt5Gui.so.5 libQt5Network.so.5 libQt5Widgets.so.5 libQt5Xml.so.5
 `
wanna to know what happened to my system? Thank you very much.

**Comment by tlze** [comment]
try offical portage. it has a newest version.
equery l -p wps-office

**Comment by resolut1on2021** [comment]
It occured the same error....

**Comment by tlze** [comment]
I have no ideas.
In my system, the libQtXml.so.4 is not found too. but wps-office works well.
It isn't any messages when I open wps-office through terminal. 

`ldd librpcetapi.*
ldd: warning: you do not have execution permission for `./librpcetapi.so'
        linux-vdso.so.1 (0x00007ffc2e5af000)
        libc++abi.so.1 => not found
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007fddfef24000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fddfef04000)
        libQtCore.so.4 => not found
        libQtNetwork.so.4 => not found
        libQtXml.so.4 => not found
        librt.so.1 => /lib64/librt.so.1 (0x00007fddfeef8000)
`

**Comment by liangyongxiang** [comment]
It's like a problem of incomplete dependency.

You can use e-file (in app-portage/pfl) to query the file, and then try to install it manually: 
```
emerge --oneshot package_name
```

If the problem is solved, pull reqeust is welcome.

**Comment by liangyongxiang** [comment]
If you are interested, you can run it again in the [test environment](https://wiki.gentoo.org/wiki/Test_environment) to ensure that the dependencies are complete

**Comment by liangyongxiang** [comment]
I tried starting from chroot stage3, but still did not reproduce your problem.

**Comment by resolut1on2021** [comment]
After a upgrade of official repos, the WPS can work well . Thanks
