### ISSUE TITLE
net-proxy/v2ray: wrong variable name in pkg_pretend()

### ISSUE THREAD

**Issue by Universebenzene** [gentoo-zh/overlay#1163]
The variable [here](https://github.com/microcai/gentoo-zh/blob/dbf7524b2993837846565d5284068cc3dc679b1c/net-proxy/v2ray/v2ray-4.40.1.ebuild#L612) should be `REPLACING_VERSIONS`,  not `REPLAING_VERSIONS`

**Comment by liangyongxiang** [comment]
天苯你来修一下?

**Comment by Universebenzene** [comment]
@liangyongxiang 这就改一个小typo而已还要发pr我寻思不至于罢……

liang菊苣直接push不是随手的事
