### ISSUE TITLE
wiki need update

### ISSUE THREAD

**Issue by liangyongxiang** [gentoo-zh/overlay#1173]
https://github.com/microcai/gentoo-zh/wiki

**Comment by Universebenzene** [comment]
@liangyongxiang 原来还有Wiki……

**Comment by liangyongxiang** [comment]
Need update : For Some Packages need more operation to use

**Comment by liangyongxiang** [comment]
放弃治疗

**Comment by Universebenzene** [comment]
@liangyongxiang 原来开了快一年了……
