### ISSUE TITLE
wps-office-11.1.0.10702在OpenRC的系统上无法启动

### ISSUE THREAD

**Issue by lizhuohua** [gentoo-zh/overlay#1195]
在使用OpenRC的系统上，输入wps命令没有任何反应。

原因在于这个版本的wps自带了一个`libdbus`文件，位于：

```
/opt/kingsoft/wps-office/office6/libdbus-1.so.3.14.6
```

删除该文件后问题解决。

我不用systemd所以尚不清楚这个解决方案对systemd用户的影响。

**Comment by Universebenzene** [comment]
@lizhuohua 绝了，我正好在今天确认了是systemd的问题（我从Arch上硬把libsystemd.so给拷到OpenRC的Gentoo上就真的跑起来了。虽然问题本身我在自己的overlay[早一个多月前](https://github.com/Universebenzene/benzene-overlay/blob/caf0091391a4f5772084df39940424cebef2819f/app-office/wps-office/wps-office-11.1.0.10702.ebuild#L140)就解决了）。 [今天正好给我自己那加了个USE控制](https://github.com/Universebenzene/benzene-overlay/commit/149df10085f194cfedbdc89820a26aa2ad7efe54) 结果正好gentoo-zh这就有人反馈了（

**Comment by microcai** [comment]
@Universebenzene wps 瞎打包。dbus 带进去干嘛？

**Comment by Universebenzene** [comment]
@microcai 去问辣鸡金山呗

**Comment by Universebenzene** [comment]
@lizhuohua 对了少回了一个问题
我在Arch上把wps bundle的libdbus全删了，依旧运行正常。所以在systemd的系统上删它也不会有问题。它会自己去系统目录找dbus库的
觉得不保险的就像我今天那样加个use判断也行

**Comment by microcai** [comment]
@Universebenzene 应该学 arch

**Comment by Universebenzene** [comment]
@microcai 怎么学……直接禁止non-systemd用户使用？

**Comment by microcai** [comment]
@Universebenzene 都讨厌 systemd 了怎么会喜欢闭源软件

**Comment by Universebenzene** [comment]
@microcai （不愧是蔡博士说着说着说着就开火了

**Comment by lizhuohua** [comment]
@Universebenzene 厉害呀！我也不会写ebuild，先退回老版本了。没办法呀，Gentoo真的太小众了。

**Comment by Universebenzene** [comment]
@lizhuohua （可以来用我的overlay呀（（无耻广告

**Comment by lizhuohua** [comment]
@Universebenzene 可以可以，我有时间研究一下
