### ISSUE TITLE
[WIP] Multilib app-i18n/fcitx

### ISSUE THREAD

**Issue by xen0n** [gentoo-zh/overlay#169]
因为还存在一些问题, 所以暂时不开PR. 主要是一些依赖关系没有 multilib 化:

```
x11-libs/gtk+:3 (!)
app-i18n/opencc
dev-qt/* (!)
x11-libs/libxkbfile
```

其中 Qt4 跟 GTK3 的问题感觉比较棘手, 尤其是 Qt4 的 multilib 化也是 WIP 状态, 感觉需要等= = GTK3 的 multilib 在 Gentoo bugzilla 居然没人提起, 不清楚是个什么状况.

PS: 我试着做了一些 Qt multilib 的工作, 一顿补丁之后 multilib 的 Qt 4.8.6 编译成功了, 但是 fcitx 貌似不喜欢 `QDBUSConnection` 等等几个类了? 我后来临时禁用了 `qt4` USE flag, 不过 build log 没保存, sigh

**Comment by microcai** [comment]
done!
