### ISSUE TITLE
Failed Patch: 11_all_system-pcre.patch - Stepmania

### ISSUE THREAD

**Issue by latot** [gentoo-zh/overlay#233]
Hi, with the update of stepmania now can't patch the file, this is the bugreport:

****\* 11_all_system-pcre.patch *****
PWD: /var/tmp/portage/games-arcade/stepmania-5.9999/work/stepmania-5.9999

PATCH COMMAND:  patch -p0 -g0 -E --no-backup-if-mismatch  < '/var/lib/layman/gentoo-zh/games-arcade/stepmania/files/11_all_system-pcre.patch'

can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:

diff -r 01e2906a1f72 configure.ac
--- a/configure.ac  Thu Jul 26 17:27:45 2012 -0500
+++ b/configure.ac  Sat Jul 28 14:50:55 2012 -0700

No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 29
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:

diff -r 01e2906a1f72 src/Makefile.am
--- a/src/Makefile.am   Thu Jul 26 17:27:45 2012 -0500
+++ b/src/Makefile.am   Sat Jul 28 14:50:55 2012 -0700

No file to patch.  Skipping patch.
3 out of 3 hunks ignored
can't find file to patch at input line 67
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:

diff -r 01e2906a1f72 src/RageUtil.cpp
--- a/src/RageUtil.cpp  Thu Jul 26 17:27:45 2012 -0500
+++ b/src/RageUtil.cpp  Sat Jul 28 14:50:55 2012 -0700

No file to patch.  Skipping patch.
1 out of 1 hunk ignored

patch program exited with status 1

PATCH COMMAND:  patch -p1 -g0 -E --no-backup-if-mismatch  < '/var/lib/layman/gentoo-zh/games-arcade/stepmania/files/11_all_system-pcre.patch'

patching file configure.ac
Hunk #1 succeeded at 387 with fuzz 2 (offset 110 lines).
patching file src/Makefile.am
Hunk #1 succeeded at 478 (offset 104 lines).
Hunk #2 FAILED at 416.
Hunk #3 succeeded at 766 with fuzz 1 (offset 111 lines).
1 out of 3 hunks FAILED -- saving rejects to file src/Makefile.am.rej
patching file src/RageUtil.cpp

patch program exited with status 1

PATCH COMMAND:  patch -p2 -g0 -E --no-backup-if-mismatch  < '/var/lib/layman/gentoo-zh/games-arcade/stepmania/files/11_all_system-pcre.patch'

can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:

diff -r 01e2906a1f72 configure.ac
--- a/configure.ac  Thu Jul 26 17:27:45 2012 -0500
+++ b/configure.ac  Sat Jul 28 14:50:55 2012 -0700

No file to patch.  Skipping patch.
1 out of 1 hunk ignored
patching file Makefile.am
Hunk #1 FAILED at 374.
Hunk #2 FAILED at 411.
Hunk #3 FAILED at 650.
3 out of 3 hunks FAILED -- saving rejects to file Makefile.am.rej
can't find file to patch at input line 67
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:

diff -r 01e2906a1f72 src/RageUtil.cpp
--- a/src/RageUtil.cpp  Thu Jul 26 17:27:45 2012 -0500
+++ b/src/RageUtil.cpp  Sat Jul 28 14:50:55 2012 -0700

No file to patch.  Skipping patch.
1 out of 1 hunk ignored

patch program exited with status 1

PATCH COMMAND:  patch -p3 -g0 -E --no-backup-if-mismatch  < '/var/lib/layman/gentoo-zh/games-arcade/stepmania/files/11_all_system-pcre.patch'

can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:

diff -r 01e2906a1f72 configure.ac
--- a/configure.ac  Thu Jul 26 17:27:45 2012 -0500
+++ b/configure.ac  Sat Jul 28 14:50:55 2012 -0700

No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 29
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:

diff -r 01e2906a1f72 src/Makefile.am
--- a/src/Makefile.am   Thu Jul 26 17:27:45 2012 -0500
+++ b/src/Makefile.am   Sat Jul 28 14:50:55 2012 -0700

No file to patch.  Skipping patch.
3 out of 3 hunks ignored
can't find file to patch at input line 67
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:

diff -r 01e2906a1f72 src/RageUtil.cpp
--- a/src/RageUtil.cpp  Thu Jul 26 17:27:45 2012 -0500
+++ b/src/RageUtil.cpp  Sat Jul 28 14:50:55 2012 -0700

No file to patch.  Skipping patch.
1 out of 1 hunk ignored

patch program exited with status 1

PATCH COMMAND:  patch -p4 -g0 -E --no-backup-if-mismatch  < '/var/lib/layman/gentoo-zh/games-arcade/stepmania/files/11_all_system-pcre.patch'

can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:

diff -r 01e2906a1f72 configure.ac
--- a/configure.ac  Thu Jul 26 17:27:45 2012 -0500
+++ b/configure.ac  Sat Jul 28 14:50:55 2012 -0700

No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 29
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:

diff -r 01e2906a1f72 src/Makefile.am
--- a/src/Makefile.am   Thu Jul 26 17:27:45 2012 -0500
+++ b/src/Makefile.am   Sat Jul 28 14:50:55 2012 -0700

No file to patch.  Skipping patch.
3 out of 3 hunks ignored
can't find file to patch at input line 67
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:

diff -r 01e2906a1f72 src/RageUtil.cpp
--- a/src/RageUtil.cpp  Thu Jul 26 17:27:45 2012 -0500
+++ b/src/RageUtil.cpp  Sat Jul 28 14:50:55 2012 -0700

No file to patch.  Skipping patch.
1 out of 1 hunk ignored

patch program exited with status 1

**Comment by biergaizi** [comment]
Got it. I will look it on weekends.

**Comment by latot** [comment]
here seems fixed:

https://github.com/thankjura/overlay/blob/master/games-arcade/stepmania/files/11_all_system-pcre.patch
