### ISSUE TITLE
360safe is really safe?

### ISSUE THREAD

**Issue by ghost** [gentoo-zh/overlay#239]
如题

**Comment by JiajunW** [comment]
The question is kind of vague. What do you really want to ask?

**Comment by ghost** [comment]
MY IDEA IS GETTING THE FUCKING CRAP 360 OUT OF OVERLAY

**Comment by microcai** [comment]
Äã²»°²×°¾ÍÐÐÁË

**Comment by ghost** [comment]
too bad......
