### ISSUE TITLE
[RFC] Remove all Deepin-Based Packages from gentoo-zh

### ISSUE THREAD

**Issue by biergaizi** [gentoo-zh/overlay#249]
There are multiple issues related to Deepin-based packages, including:
- #200
- #231 

And more unknown issues.

It is very hard to maintain them, even in AUR, most of the packages was abandoned. Since nobody maintains Deepin-based Software in gentoo-zh, we probably should remove them instead of left the broken packages inside the repository until they have a maintainer.

**Comment by biergaizi** [comment]
If others have no further comments, I will perform it in 7 days.

**Comment by JiajunW** [comment]
+1 from me.

Furthermore, there is no effective way to track the maintainer of a package. I think it is better to include the `metadata.xml` to record the related info.
BTW I will open a new issue to discuss the `metadata.xml` stuff.

**Comment by microcai** [comment]
nagetive 

don't remove package when some one is still using it.
if the build brokes, please report the bug.

**Comment by biergaizi** [comment]
Okay, just keep them masked to prevent new users to install them by accident.

**Comment by biergaizi** [comment]
The problem is the maintainers who know Deepin well is gone at least for 6 months, nobody else knows how to workaround those issues. And the upstream still calls `sudo` in the build scripts, :-1:

**Comment by biergaizi** [comment]
If there are still no maintainer at the end of 2015, I'll remove all the packages.

**Comment by biergaizi** [comment]
Okay, this is 2016 now and we still do not have any maintainers, and all those broken packages were masked for a whole year, nobody did install them.

Purge them all!
