### ISSUE TITLE
对于托管在 Github 上的没有声明 License 的 Public Repo 怎么处理?

### ISSUE THREAD

**Issue by zhustec** [gentoo-zh/overlay#267]
只能向作者发 ISSUE 等待作者添加 LICENSE ?

**Comment by biergaizi** [comment]
Portage 系统里有个 LICENSE 叫 `all-rights-reserved`。

**Comment by biergaizi** [comment]
> All rights reserved.
> 
> This package has an explicit "all rights reserved" clause, or comes
> without any license, or only with a disclaimer. This means that you
> have only the rights that are granted to you by law. If you have
> lawfully acquired a copy of the program (e.g., by buying it or by
> downloading it from the author's site) then in many legislations you
> are allowed to compile it, run it, make a backup, and to patch it as
> necessary, without permission from the copyright holder.
> 
> Redistribution of the program is not allowed.
> 
> Disclaimer: Presumably, the above applies to the United States and
> countries in the European Union at least. However, it is your own
> responsibility to obey your country's laws.

很实用吧～任何授权不明的软件包都可以认为是作者保留所有权力，使用者责任自负。

**Comment by zhustec** [comment]
确实很实用, 感谢 :+1:
