### ISSUE TITLE
Overlay 中的 dev-util/ack2 跟 Portage 中的 sys-apps/ack 重复了吧？

### ISSUE THREAD

**Issue by wangbin** [gentoo-zh/overlay#271]
Portage 中已经有 sys-apps/ack-2.14 的 ebuild 了，而且官网上的[安装说明](http://beyondgrep.com/install/)也有提到：

```
Gentoo
    Package "sys-apps/ack"
```

请管理员确认一下吧，我不太清楚 Overlay 中的 [ack2-2.14.ebuild](https://github.com/microcai/gentoo-zh/blob/master/dev-util/ack2/ack2-2.14.ebuild) 跟 Portage 里面的有什么不一样的地方？

**Comment by biergaizi** [comment]
请维护者 @wittyfox 来解答。

**Comment by zhustec** [comment]
是这样的，我提交的那个 dev-util/ack2 提供了 Live 版的选择，并且有一个 standalone 的 USE 用于生成一个
Portable 版本的 ack。我曾经考虑将 ack2 合并入 sys-apps/ack，但是我觉得两个 Ebuild
风格是不一样的，所以在我点下发 PR 的前一秒决定不合并了，而我也觉得 ack2 放在 dev-util 里很适合，所以一直保留在这里，当然如果
maintainer 觉得没有必要，为了不产生混淆，也可以合并。或者说明，我会发个 PR 把这两个合并。

再顺便说下我添加的 dev-util/global 与官方 Portage 树重复的原因：

global 中的 gtags 默认只支持 6 种语言，但是通过开启 ctags 扩展可以使用 ctags 作为解析器，但是要使 gtags 支持
ctags 扩展，需要 global 编译 `--enable-exuberant-ctags` 支持，但是官方 Portage 树里的 global
默认既不添加这个编译选项，也没有提供 USE 提供选择。当然可以使用 `EXTRA_CONF` 安装

``` bash
sudo EXTRA_ECONF='--with-exuberant-ctags=/usr/bin/exuberant-ctags' emerge
-av global
```

但是这只是临时解决方法，我曾经想联系维护者建议添加选项，但是 Gentoo Packages 网站没有提供一个像 Arch Linux
那样的用户与用户与维护者交流的平台，所以我就提交了 dev-util/global ，比 Portage 树里的 global 多添加了一个
ctags 的 USE 用于使 global 支持 ctags 扩展。

2015-03-13 18:05 GMT+08:00 Tom Li notifications@github.com:

**Comment by biergaizi** [comment]
@wittyfox P.S：用户若想与开发者交流 feature request，可以直接报告 Bug。这是官方包，而不是 AUR。

**Comment by microcai** [comment]
提供官方没有的功能是可以的。 但是要使用相同的名字， 放到相同的 category。额外的功能使用 USE 启用。保持和官方相同。如果通过 USE 无法保持和官方兼容， 则  mask 掉。 portage 会自动 fallback 到官方仓库里的版本。

**Comment by zhustec** [comment]
那你觉得需不需要合并呢？如果需要，我下周一会发 PR。

在 2015年3月13日 下午7:40，microcai notifications@github.com写道：

**Comment by microcai** [comment]
当然是要合并的. 否则如果装了 ack 岂不是要 file conflict ?

**Comment by liangyongxiang** [comment]
package drop: 24eb3137d49dbb35cff280ed5ca6a53a1f69bda6
