### ISSUE TITLE
Please remove sys-apps/pacman from package.mask

### ISSUE THREAD

**Issue by hartwork** [gentoo-zh/overlay#276]
I just discovered that the only reason why pacman ist hard masked on a setup of mine is because that machine makes use of the gentoo-zh overlay:

https://github.com/microcai/gentoo-zh/blob/master/profiles/package.mask#L35

Please remove `sys-apps/pacman` from package.mask. Thank you!

**Comment by microcai** [comment]
fixed!

**Comment by hartwork** [comment]
That was quick. Thank you!
