### ISSUE TITLE
gnulib's manifest is volatile

### ISSUE THREAD

**Issue by JiajunW** [gentoo-zh/overlay#282]
gnulib-0.1.tar.gz in this media-gfx/fontforge is a snapshot and the checksum varies from time to time. We'd better host the snapshot or find a better way to avoid the manifest problem.

BTW, I have no idea why they (gnulib and uthash) are needed since fontforge on archlinux does not require them.

**Comment by microcai** [comment]
the build script will download gnulib if they are not there.

**Comment by microcai** [comment]
and it is problematic, since portage forbid the network access ouside pkg_fetch .

**Comment by microcai** [comment]
fixed!
