### ISSUE TITLE
media-sound/kalsamix, dev-util/kdevelop-kernel, media-video/kvideoencoder: EAPI=4 is not supported

### ISSUE THREAD

**Issue by CasperVector** [gentoo-zh/overlay#284]
As the title, any ebuild that (either directly or indirectly) inherits `kde4-functions.eclass` is forced by the elcass to use EAPI 5.  This affects `egencache`, which complains about those invalid ebuilds.

I have commit proviledge to this repository, but do not use these packages, so can't test the result if I just apply `s/^EAPI=.*$/EAPI=5/g` to the ebuilds.  Can anyone using these packages test and fix this?

**Comment by microcai** [comment]
EAPI does not affect built binary. if it compiles and installs,then it's fine.

run

```
ebuild  [patch to .ebuild file]  compile install 
```

to test, it won't install into your system

**Comment by CasperVector** [comment]
They will bring in lots of KDE dependencies (which I try to avoid), even if I do not `merge` them...

**Comment by CasperVector** [comment]
There are no comments from developers for a long time...
Looking at the ebuilds, the code is quite simple, so just set EAPI to 5 without other modifications would  probably be safe.
Will commit the changes then; feel free to reopen this issue and comment, should there be any problem.

**Comment by CasperVector** [comment]
`gnome-extra/gdmap` inherits `gnome2.eclass`, which now requires EAPI 5.
Following the above-mentioned procedure because the ebuild seems simple enough.
