### ISSUE TITLE
有道词典官方版有了,毕业答辩了,没有时间,谁写个脚本吧

### ISSUE THREAD

**Issue by hiapk** [gentoo-zh/overlay#288]
http://cidian.youdao.com/index-linux.html  这是官方地址

**Comment by microcai** [comment]
nice

**Comment by qifly** [comment]
写了一个，在https://github.com/qifly/gentoo-zh/tree/master/app-dicts/youdao-dict ，还没提交过来。还有用到的一个依赖python3-xlib也写了。方便的话测试一下，发现问题再修改。

**Comment by zhtengw** [comment]
Merge fail. In python3-xlib ebuilds, when use distutils-r1 eclass, SUPPORT_PYTHON_ABIS, RESTRICT_PYTHON_ABIS and PYTHON_MODNAME should be removed. Youdao-dict needs the webkit USE flag of PyQt5.
And I try to fix it.
https://github.com/zhtengw/gentoo-zh/commit/081094886a1ce68600ae35c51f9b3b79dbd44030

**Comment by qifly** [comment]
@zhtengw Greate,Thanks for share.
