### ISSUE TITLE
dev-lang/coffee-script: npm.eclass could not be found by inherit()

### ISSUE THREAD

**Issue by CasperVector** [gentoo-zh/overlay#291]
As the title, `dev-lang/coffee-script` inherits `npm`, which does not exist in official Portage or `gentoo-zh`.
This makes the ebuild actually invalid, and causes `egencache(1)` to complain loudly.

**Comment by CasperVector** [comment]
Dropping the ebuild now since nobody else seems to care.
Feel free to reopen if you can provide `npm.eclass`.

**Comment by zhustec** [comment]
事实上，这个包是我添加的，本来是能工作的，后来被修改了之后就工作不能了。 https://github.com/microcai/gentoo-zh/commit/21c9180bf35e91f08e35970cb1ca3f7a312a0330
