### ISSUE TITLE
Stepmania - cmake

### ISSUE THREAD

**Issue by latot** [gentoo-zh/overlay#298]
Hi, its posible update the stepmania ebuild for cmake?, now is available.

Thx.

**Comment by biergaizi** [comment]
Now it seems that autotools is completely deprecated and broken in Stepmania. It's the final time for me to migrate...

**Comment by latot** [comment]
Hi, i think with this you can save a little time, this ebuild is incomplete (but works fine), missing the use in the cmakeargs, and it don't use the ext-datadir patch because it doesn't works on cmake, actually sm only works with the bundled ffmpeg, if you want to use system ffmpeg you need downgrade to ffmpeg-2.1 and it doesn't posible with the actually versions on gentoo.

https://gist.github.com/latot/3b0b8f350bc420378a1c

**Comment by latot** [comment]
the avframe patch was merged in the master of sm, the patch most be removed.
https://github.com/stepmania/stepmania/pull/331

**Comment by biergaizi** [comment]
Got it. I'll start working on it this weekends. Thanks for your help with these information.

**Comment by latot** [comment]
Hi, new info, system ffmpeg works with  ffmpeg-2.8, tis available for gentoo.

**Comment by biergaizi** [comment]
Yes, it SHOULD work with system-ffmpeg, but If I enable `WITH_SYSTEM_FFMPEG`, the `<time.h>` of FFmpeg short-circuits the standard UNIX header `<time.h>`, and it doesn't build.

**Comment by latot** [comment]
i'm actually using sm with system_ffmpeg and works fine (upgrade to ffmpeg-2.8), sm its working to upgrade officially to ffmpeg-2.8 https://github.com/stepmania/stepmania/pull/882, linux its the only platform working for now with this version, if you will try to use it but bundled you will need add -llzma to the linker.
