### ISSUE TITLE
cutegram "qtmultimedia fails with gstreamer" in depend ebuild solved.

### ISSUE THREAD

**Issue by Techwolf** [gentoo-zh/overlay#313]
Thanks to google, found this web page: https://github.com/GoldenCheetah/GoldenCheetah/issues/942

Bascially what is causing the gstreamer issue is webkit built with gstreamer 1.0 and qtmultimedia with 0.10.

Recommenced fix is change dev-qt/qtmultimedia:5[qml,-gstreamer] in libqtelegram-ae-0.5.0.ebuild to dev-qt/qtmultimedia:5[qml]

And change dev-qt/qtwebkit:5 in cutegram-2.5.0.ebuild to dev-qt/qtwebkit:5[-gstreamer]

This will forced qtwebkit to be either build with use flag gstreamer010 or use flag multimedia that pulls in qumultimedia that will be built with gstreamer 0.10.

This will fix the cutegram hanging after entering phone number with this error in console: "(cutegram:3342): GStreamer-CRITICAL **: gst_element_class_set_details_simple: assertion 'GST_IS_ELEMENT_CLASS (klass)' failed"

**Comment by microcai** [comment]
we need to wait until qt-5.5 hit the tree. then qtmultimedia can be built with gstreamer 1.0

**Comment by liangyongxiang** [comment]
Close old issue
