### ISSUE TITLE
plase do not call "use" outside package setup/compile/install phrase

### ISSUE THREAD

**Issue by microcai** [gentoo-zh/overlay#315]
see https://bugs.gentoo.org/show_bug.cgi?id=557682

**Comment by microcai** [comment]
now I've reduced to only one package that cause problem: e-sources.

**Comment by ghost** [comment]
可以先割了 改好再接回去

**Comment by microcai** [comment]
@biergaizi  I'm going to remove e-sources until you fix the problem. any objection ?

**Comment by biergaizi** [comment]
Fixed in ae7fdbdedb79bb13fa1de2c3209a4b1915183d5e. But I can't maintain it anymore, looking for new maintainer...
