### ISSUE TITLE
New ebuild firefox-kde-opensuse

### ISSUE THREAD

**Issue by WallanceLee** [gentoo-zh/overlay#320]
For a long time, firefox doesn't have a good integration of KDE.So is it possible to write a new ebuild of firefox-kde-opensuse to improve this.ArchLinux has this software in its AUR.
https://aur.archlinux.org/packages/firefox-kde-opensuse/

**Comment by zhtengw** [comment]
Actually, you can install firefox-kde-opensuse via bobwya overlay.

**Comment by liangyongxiang** [comment]
Close old issue
