### ISSUE TITLE
kde-plasma/kcm-fcitx depends on app-i18n/fcitx-qt5?

### ISSUE THREAD

**Issue by vizv** [gentoo-zh/overlay#322]
I need install `app-i18n/fcitx-qt5` before `kde-plasma/kcm-fcitx`, should we add `app-i18n/fcitx-qt5` as a dependency?

**Comment by microcai** [comment]
yes

2015-08-30 0:38 GMT+08:00 Wenxuan Zhao notifications@github.com:

**Comment by biergaizi** [comment]
More and more stuff are migrating to KDE5/Qt5, including applications, developers, users, and of course portage packages.
