### ISSUE TITLE
media-sound/netease-musicbox needs more dependences

### ISSUE THREAD

**Issue by ghost** [gentoo-zh/overlay#334]
并不很确定。起码在我的gentoo中没法像ubuntu那样，猜测是缺少依赖。
似乎无法拉取歌曲信息，比如长度和歌词。
Maybe dev-python/pip is needed?

**Comment by taocp** [comment]
这个咨询原作者是最方便、准确的事情。。
根据我的（xue）经（de）验（jiaoxun），尽量避免用pip装东西，可能会和Portage冲突。

**Comment by ghost** [comment]
已解决
ebuild缺少依赖media-sound/mpg123
请馆里猿及时修正XD

BTW.我的/gnome/systemd profile确确实实之前没有装过这个包。
同学的KDE环境似乎并不缺少这个包，不知道蹭着什么依赖进来了233
