### ISSUE TITLE
app-laptop/asus-keyboard-backlight  add systemD 

### ISSUE THREAD

**Issue by necrose99** [gentoo-zh/overlay#346]
https://github.com/necrose99/necromancy-overlay/blob/master/app-laptop/asus-keyboard-backlight/asus-keyboard-backlight-0.1.ebuild
this is my lame attempt at a SystemD supportive ebuild , could be re-factored for Google upstart etc or any other init system that is not openrc, or sysvinit.
So far only thing working about it is frustration.
So I am Giving what I have. Hopefully With collaboration , I can achieve the desired outcome. 
ASUS Republic of Gamers G73SW.  My own laptop. 
Sabayon Linux (Gentoo Variant) 
instead of directly installing to previous ebuild locations ..
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=asus-kbd-backlight
I took a clue from Arch Linux...
/usr/bin/.... however added symbolic links to old directories.
thus any other init system is more readily added. 
A: Symbolically linked B: similar to SystemD called executable from service/configuration file more  
easily. 
As well if user needs to /usr/bin a tad easier to execute manually. 
changed header to match git EAPI 5 style as cvs header$ is dead. 

Note:Google Translator was used, other than please or  thanks, or a few trial pleasantries I don't speak enough Mandarin/Cantonese  to matter,  Japanese or Spanish,etc I am more useful.
這是我的跛腳企圖在SystemD支持的ebuild，可以重新分解為谷歌新貴等或任何其他的初始化系統未OpenRC誕生了，或者sysvinit的。
到目前為止，唯一的工作大約是無奈。
所以，我給我有什麼。希望通過合作，我可以達到理想的效果。
遊戲玩家G73SW華碩共和國。我自己的筆記本電腦。
芭雍Linux的（Gentoo的變體）
而不是直接安​​裝到以前的ebuild位置..
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=asus-kbd-backlight
我從Arch Linux的一個線索...
在/ usr /斌/ ....但是添加符號鏈接到舊目錄。
因此，任何其他的初始化系統更容易增加。
答：象徵鏈接B：類似SystemD稱為從服務/配置文件可執行更​​多
容易。
至於如果用戶需要以及到/ usr / bin中稍微容易手動執行。
改變的報頭相匹配的git EAPI 5風格CVS頭$已經死了。

注：谷歌翻譯用，不是取悅或感謝，或幾個試驗寒暄我不會說普通話不夠/廣東話啦，日語或西班牙語等，等我更有用。

```

# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=5

DESCRIPTION="Configure the brightness of the keyboard's backlight on ASUS
laptops."
HOMEPAGE="http://projects.flogisoft.com/asus-keyboard-backlight/"
SRC_URI="http://projects.flogisoft.com/${PN}/download/${PN}_${PV}_src.tar.gz
https://launchpad.net/${PN}/trunk/0.1/+download/${PN}_${PV}_0.1_src.tar.gz"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~*"
IUSE="-sys-apps/systemd"

RDEPEND="${DEPEND}
    dev-lang/python
    sys-power/acpid
    systemd? ( sys-apps/systemd )"

S="${WORKDIR}/asus-kbd-backlight-${PV}"
# write for systemD or other init Support , changed to bin path & Add Symlinks if using openrc,etc. better to be init neutral. 
src_install(){
    #Install
    #$1 : the output path, if different of /
    #ACPI events
    dodir /etc/acpi/events/
    cp -v ./events/* "$D"/etc/acpi/events/
    #ACPI script
    cp -v ./code/asus-kbd-backlight.py "$D"/usr/bin/asus-kbd-backlight.py
    dosym /usr/bin/asus-kbd-backlight.py "$D"/etc/acpi/asus-kbd-backlight.py
    chmod 755 "$D"/usr/bin/asus-kbd-backlight.py
    #Resume script
    dodir /etc/pm/sleep.d/
    cp -v ./code/asus-kbd-backlight_resume.sh "$D"/usr/bin/asus-kbd-backlight_resume
    dosym /usr/bin/asus-kbd-backlight_resume /etc/pm/sleep.d/80_asus-kbd-backlight
    chmod 755 "$D"/usr/bin/asus-kbd-backlight_resume
    #Init script
    dodir   /etc/init.d/
    cp -v ./code/asus-kbd-backlight_init.sh  "$D"/usr/bin/asus-kbd-backlight
    dosym /usr/bin/asus-kbd-backlight /etc/init.d/asus-kbd-backlight
    chmod 755 "$D"/usr/bin/asus-kbd-backlight

    #Bak
    dodir /var/lib/asus-kbd-backlight/
    echo 1 > "$D"/var/lib/asus-kbd-backlight/brightness
}
## ADD In Systemd Gentoo Devs Say its better to Install them all.
# write for systemD use= if not using SystemD or going to Migrate to it no point in adding extra crap if user dont want it.
pkg_service() {
    if USE="systemd?"
inherit systemd
        # write the systemd unit file
        cat <<-'EOF' > /usr/lib/systemd/system/asus-kbd-backlight.service
        [Unit]
        Description=Allow user access to keyboard backlight
        After=systemd-udevd.service

        [Service]
        ExecStart=/usr/bin/asus-kbd-backlight allowusers

        [Install]
        WantedBy=multi-user.target 
        EOF

dosym   /usr/lib/systemd/system/asus-kbd-backlight.service /etc/systemd/system/asus-kbd-backlight.service
systemd_enable_service /usr/lib/systemd/system/asus-kbd-backlight.service 
    else
    fi
}
```

**Comment by biergaizi** [comment]
```
    if USE="systemd?"
inherit systemd
        # write the systemd unit file
        cat <<-'EOF' > /usr/lib/systemd/system/asus-kbd-backlight.service
        [Unit]
        Description=Allow user access to keyboard backlight
        After=systemd-udevd.service

        [Service]
        ExecStart=/usr/bin/asus-kbd-backlight allowusers

        [Install]
        WantedBy=multi-user.target 
        EOF
```

Why don't you put this service file to `files/` and copy it from `${FILESDIR}`?

**Comment by necrose99** [comment]
oh i did however the SRC_URI=fail 
https://github.com/necrose99/necromancy-overlay/blob/master/app-laptop/asus-keyboard-backlight/Files/asus-kbd-backlight.service
however i will peg it. anycase i'm monkeying with it , since I like my kb lights working with sabayon (gentoo/sytemd) i'd figure i'd share what i got. 
i'll add the ${FILESDIR} so i can do the unit file.

**Comment by biergaizi** [comment]
However, I don't have hardware to test it. But feel free to send pull request to here :)

**Comment by biergaizi** [comment]
No Pull Request for a year, close.

**Comment by necrose99** [comment]
my apologizes , really very **backlogged** , moved , had a job on the road , hotel/travel hear or their kinda kills the wage.  being a road warrior kills your time also. 
just need to get a drive and test.  (lovely the unit dual boots from 2 drives normally. )  just i've done so many compiles , i kill drives , I need to get a server with redundant drives /zfs mirroring for that kind of dirty work. 

been so bleeping busy to go get a **2nd replacement hard drive or SSD** preferably, or forget or have bills before getting a new drive... however since i have some downtime , severance I can get caught up. 

 https://github.com/necrose99/necromancy-overlay
made an issue (reminder )  I will to add a pull after I've tested, since I'm a fan of Asus ROG units, it's kinda a need to tinker it.  good for gaming as well the new liquid cooled twin GPU's also make for "swiss-cheese" of security key hunting in wifi pentesting..  (helps find the holes faster)..  (salivating over the liquid dock ROG.... but I'm broke-ish for the moment  , so my older **G73SW** will have to do. )
