### ISSUE TITLE
net-proxy/lantern depends on sys-apps/systemd

### ISSUE THREAD

**Issue by NineSong** [gentoo-zh/overlay#352]
Hi, I've noticed that net-proxy/lantern depends on sys-apps/systemd. Why does lantern depends on systemd? You may want to autostart lantern, but some users may not, like me. Achieving this is easy, so would it be nicer to leave the control to the users? I'm an openrc user, pulling in systemd for me is irrational.
What's more, I tried to emerge lantern with --nodeps and succeeded. That is to say, systemd is not a dependency at all.
By the way, emerge says that /usr/bin/lantern is an invalid symbolic link. It attempts to link to /usr/lib/lantern/lantern.sh, which is not extracted to the directory.

**Comment by aieu** [comment]
depend systemd, that's not decided by me, `ldd` told that lanter-binary depend on systemd...
and you are right, lantern can run without systemd, mybe adding systemd use flag is better.. 

about lantern.sh, I found that it would update lantern itself without by emerge.. 

so everyone together to discuss how to handle with lantern.sh

@microcai

**Comment by aieu** [comment]
@NineSong can you test the latest lantern ebuild?

@microcai some may add the source lantern ebuild to build, so we should mv it to net-proxy/lantern-binary ?

**Comment by JiajunW** [comment]
@registe I think this package should be named `net-proxy/lantern-bin`.

**Comment by aieu** [comment]
@JiajunW yeap... i also think that so this morning.

**Comment by NineSong** [comment]
@registe At first it says

```
!!! Fetched file: lantern-installer-64-bit.deb VERIFY FAILED!
!!! Reason: Insufficient data for checksum verification
!!! Got:
!!! Expected: MD5 RMD160 SHA1 SHA256 SHA512 WHIRLPOOL
```

After I executed

```
root# ebuild /var/lib/layman/gentoo-zh/net-proxy/lantern/lantern-2.0.10.ebuild digest
```

it worked well. Thanks.

**Comment by aieu** [comment]
@NineSong my fault, sorry
and now, use net-proxy/lantern-bin instead of net-proxy/lantern.
