### ISSUE TITLE
app-i18n/fcitx: build fail

### ISSUE THREAD

**Issue by RobinDX** [gentoo-zh/overlay#360]
Emerging (1 of 1) app-i18n/fcitx-4.2.9::gentoo
- fcitx-4.2.9_dict.tar.xz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                                           [ ok ]
  >>> Unpacking source...
  >>> Unpacking fcitx-4.2.9_dict.tar.xz to /var/tmp/portage/app-i18n/fcitx-4.2.9/work
  >>> Source unpacked in /var/tmp/portage/app-i18n/fcitx-4.2.9/work
  >>> Preparing source in /var/tmp/portage/app-i18n/fcitx-4.2.9/work/fcitx-4.2.9 ...
  >>> Source prepared.
  >>> Configuring source in /var/tmp/portage/app-i18n/fcitx-4.2.9/work/fcitx-4.2.9 ...
  >>> Working in BUILD_DIR: "/var/tmp/portage/app-i18n/fcitx-4.2.9/work/fcitx-4.2.9_build"
- ERROR: app-i18n/fcitx-4.2.9::gentoo failed (configure phase):
-   Declaring mycmakeargs as a variable is banned in EAPI=5. Please use an array instead.
- 
- Call stack:
-     ebuild.sh, line  133:  Called src_configure
-   environment, line 3349:  Called cmake-utils_src_configure
-   environment, line  842:  Called _cmake_execute_optionally 'src_configure'
-   environment, line  377:  Called enable_cmake-utils_src_configure
-   environment, line 1163:  Called die
- The specific snippet of code:
-                   die "Declaring mycmakeargs as a variable is banned in EAPI=${EAPI}. Please use an array instead.";
- 
- If you need support, post the output of `emerge --info '=app-i18n/fcitx-4.2.9::gentoo'`,
- the complete build log and the output of `emerge -pqv '=app-i18n/fcitx-4.2.9::gentoo'`.
- The complete build log is located at '/var/tmp/portage/app-i18n/fcitx-4.2.9/temp/build.log'.
- The ebuild environment file is located at '/var/tmp/portage/app-i18n/fcitx-4.2.9/temp/environment'.
- Working directory: '/var/tmp/portage/app-i18n/fcitx-4.2.9/work/fcitx-4.2.9'
- S: '/var/tmp/portage/app-i18n/fcitx-4.2.9/work/fcitx-4.2.9'

**Comment by RobinDX** [comment]
Declaring mycmakeargs as a variable is banned in EAPI=5.

**Comment by RobinDX** [comment]
I dont kown why.
But after I "rm -rf /usr/portage && emerge --sync ",it works.

**Comment by microcai** [comment]
because you're using fcitc from gentoo not from gentoo-zh

2016-01-28 16:28 GMT+08:00 RobinDX notifications@github.com:
