### ISSUE TITLE
能否升级下wiznote，现在新版到2.3.3了

### ISSUE THREAD

**Issue by hsyan2008** [gentoo-zh/overlay#362]
能否升级下wiznote，现在新版到2.3.3了，9999那个又安装失败

**Comment by OwenChia** [comment]
安装失败貌似是因为他们默认 Qt5 了，依赖项不太一样。
不过我试了下手动安装好依赖然后编译也报错了，怀疑是依赖的 Qt 版本比较高，但是暂时还没找到说明。

另外看了下他们项目页面，Releases 里只到 v2.1.0……

**Comment by OwenChia** [comment]
暂时没法升级，原因是 v2.3.3 版本需要依赖 Qt 5.7，这个版本在 Gentoo 官方仓库中暂时还是 mask 状态。

**Comment by zhaojunhai** [comment]
现在wiz升级到`2.4`了，不知道啥时候Gentoo的 **Qt5.7** unmask。：）

**Comment by zhaojunhai** [comment]
已经inProgress了，赞一个：）

**Comment by zhtengw** [comment]
@OwenChia ，官方仓库的Qt5.7已经是~amd64 ~x86 KERWORDS了，目前我机器上的版本就是Qt5.7.1
![2016-12-19 09 49 16](https://cloud.githubusercontent.com/assets/3148769/21298831/6f566cfe-c5d0-11e6-9f75-8c2f36b233e8.png)

**Comment by zhtengw** [comment]
I have submitted a pull request https://github.com/microcai/gentoo-zh/pull/415 .

**Comment by biergaizi** [comment]
The pull request has been merged. 👍

**Comment by biergaizi** [comment]
Feel free to file a new issue if you encounter any problems.
