### ISSUE TITLE
关于 net-proxy/shadowsocks-qt5、net-proxy/libQtShadowsocks 的问题

### ISSUE THREAD

**Issue by OwenChia** [gentoo-zh/overlay#364]
首先是因为[这个](https://github.com/gentoo/qt/commit/8aae5020b96f9e252e9f3a562c89551493877bba)，qt5-build 现在只能用在 dev-qt 目录下的 ebuild 中。
然后 net-proxy/shadowsocks-qt5、net-proxy/libQtShadowsocks 中继承了 qt5-build ，导致

```
!!! All ebuilds that could satisfy "libQtShadowsocks" have been masked.
!!! One of the following masked packages is required to complete your request:
- net-proxy/libQtShadowsocks-1.8.3::gentoo-zh (masked by: corruption)
```

**Comment by aieu** [comment]
大略修复了下，过年了，没时间仔细看了。
新年快乐！

**Comment by OwenChia** [comment]
@registe 新年快乐！
