### ISSUE TITLE
gcin-2.8.4 released

### ISSUE THREAD

**Issue by samuelololol** [gentoo-zh/overlay#370]
http://hyperrate.com/thread.php?tid=31823

**Comment by samuelololol** [comment]
I've disabled the qt4 flag but it still fail. I found that there is a new option `use_qt5` for `configure` but not in this ebuild as a USE flag.

By the way, gcin-2.8.5 was just released at Feb-01-2017 ( http://hyperrate.com/gcin-source/ )

**Comment by microcai** [comment]
please report build failure to upstream. this is a upstream bug.

**Comment by samuelololol** [comment]
@microcai I've udpated the comment, the root cause is `use_qt5`.
