### ISSUE TITLE
net-proxy/shadowsocks-libev: no-root processes can't bind ports below 1024

### ISSUE THREAD

**Issue by aieu** [gentoo-zh/overlay#373]
maybe someone run shadowsocks-libev server on the port 443 or other that below 1024.

so should we use User=root in the systemd unit file?

**Comment by JiajunW** [comment]
I would not recommend that.

If some one want to use a port below than 1024, he could overwrite this option using `systemctl edit`.

Typically this service does not require super user privilege, so it is not necessary to have it run under root user.
And root privilege in default config could be dangerous if there exists some vulnerabilities in the software.
