### ISSUE TITLE
media-sound/kwplayer不安装任何文件

### ISSUE THREAD

**Issue by y-usuzumi** [gentoo-zh/overlay#374]
和PYTHON_SINGLE_TARGET有关。

我配置的PYTHON_SINGLE_TARGET是python2_7，但PYTHON_TARGETS里配了python3_4和python3_5。似乎应该检查PYTHON_TARGETS而不是PYTHON_SINGLE_TARGETS。

即便是检查PYTHON_SINGLE_TARGET，若配置了python3_4及python3_5以外的值，应该依赖检查报错而不是安装成功。

**Comment by y-usuzumi** [comment]
现在是通过在/etc/portage/package.use中添加
`media-sound/kwplayer python_single_target_python3_4`
进行缓解。

**Comment by RevySR** [comment]
media-sound/kwplayer has removed

So I close the issue
