### ISSUE TITLE
buildapp error

### ISSUE THREAD

**Issue by VZIKL** [gentoo-zh/overlay#382]
Saving to: ‘/usr/portage/distfiles/buildapp-1.4.6.tgz’

/usr/portage/distfi 100%[===================>]  16.00K  27.0KB/s    in 0.6s    

2016-06-06 18:55:04 (27.0 KB/s) - ‘/usr/portage/distfiles/buildapp-1.4.6.tgz’ saved [16389/16389]

!!! Fetched file: buildapp-1.4.6.tgz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      16389
!!! Expected: 15813
Refetching... File renamed to '/usr/portage/distfiles/buildapp-1.4.6.tgz._checksum_failure_.k0l5vG'

!!! Couldn't download 'buildapp-1.4.6.tgz'. Aborting.
- Fetch failed for 'dev-lisp/buildapp-1.4.6', Log file:
-  '/var/tmp/portage/dev-lisp/buildapp-1.4.6/temp/build.log'

> > > Failed to emerge dev-lisp/buildapp-1.4.6, Log file:
> > > 
> > >  '/var/tmp/portage/dev-lisp/buildapp-1.4.6/temp/build.log'
- Messages for package dev-lisp/buildapp-1.4.6:
- Fetch failed for 'dev-lisp/buildapp-1.4.6', Log file:
-  '/var/tmp/portage/dev-lisp/buildapp-1.4.6/temp/build.log'

**Comment by OwenChia** [comment]
看了下下载链接，好像是因为没有指明版本，所以导致下载到的不是 1.4.6 版本的。

没装 lisp，麻烦你测试下[这个](https://gist.github.com/OwenChia/e4f478448a54736b79bd5ee48274aebb)可不可以用。

**Comment by VZIKL** [comment]
问题应该是Manifest文件的SHA值不匹配并且下载链接默认最新版 ebuild buildapp.ebuild digest更新下manifest就行

**Comment by OwenChia** [comment]
@VZIKL 是这样没错，但是 ebuild 里没指定下载的版本的话，会导致实际安装与 ebuild 的版本不一致，以后还是会出现这样的问题吧？

**Comment by VZIKL** [comment]
= =所以等他出了新的就ebuild改下sha咯 那玩意貌似只有最新的下载链接

**Comment by OwenChia** [comment]
你可以看下我贴那个 gist，它在 github 上发布的是有版本号的。

**Comment by VZIKL** [comment]
@OwenChia SRC_URI应该这样写吧 SRC_URI="https://codeload.github.com/xach/buildapp/tar.gz/release-${PV} -> ${P}.tar.gz"
我自己测试了下这个能用

**Comment by OwenChia** [comment]
#407 已提交
