### ISSUE TITLE
media-sound/netease-cloud-music 不停网络错误

### ISSUE THREAD

**Issue by KireinaHoro** [gentoo-zh/overlay#391]
尝试一下私人FM就能发现。
貌似曾经缓存过的歌曲就不会。
网络错误后重新回去再播放同一首歌曲就又可以正常播放了。

**Comment by KireinaHoro** [comment]
没有播放过的歌曲如果先下载再播放就不会有问题。（直接播放则会第一次网络错误，之后都没问题）

**Comment by vizv** [comment]
请问你在国内么？已知在国外用代理或者改 hosts 的方法可能会导致这个原因，因为传过来的是文件而不是流……

**Comment by KireinaHoro** [comment]
并不。我还试过挂VPN（日本），这种情况下会正常提示您所在的地区无法使用。

**Comment by PiraHzq** [comment]
我也一直出现类似的问题，然后用起了网页版本

**Comment by vizv** [comment]
这个月底我才有时间看这个问题……T_T，我想知道在 Ubuntu 或者 Deepin 上有这个问题么？

**Comment by KireinaHoro** [comment]
不清楚 - -
Arch 沒有（

**Comment by vizv** [comment]
@xubin990510 ty，估计抽空要去看看 aur 他们怎么搞的

**Comment by vizv** [comment]
@xubin990510 刚刚让清风老师测了，他说没问题。你能把 `emerge --info` 和完整的构建 log 发一下么？还有你用的 qt 还是 gtk？

**Comment by KireinaHoro** [comment]
時間太久遠了 咱現在沒在用gentoo - -
抱歉（
