### ISSUE TITLE
求更新永中office 

### ISSUE THREAD

**Issue by Lookinfres** [gentoo-zh/overlay#404]
app/yozooffice现在还是2012版本，最新已经2016了

**Comment by hiapk** [comment]
新版的永中有图形的安装界面，可以直接下载安装包然后解压运行安装～，我尝试看了一下下载的压缩包的结构，有一堆不知道怎么解压的压缩包，所以脚本不知道怎么处理，不知道老大们有没有什么解决方法。@microcai
