### ISSUE TITLE
app-misc/gpick source files no longer available

### ISSUE THREAD

**Issue by aewne** [gentoo-zh/overlay#416]
Seems to have been migrated from Google Code to Github.

See https://github.com/thezbyg/gpick

> Downloading 'http://gpick.googlecode.com/files/gpick_0.2.4.tar.gz'
--2016-12-22 14:37:01--  http://gpick.googlecode.com/files/gpick_0.2.4.tar.gz
Resolving gpick.googlecode.com... 74.125.131.82, 2a00:1450:4010:c06::52
Connecting to gpick.googlecode.com|74.125.131.82|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-22 14:37:02 ERROR 404: Not Found.
!!! Couldn't download 'gpick_0.2.4.tar.gz'. Aborting.

**Comment by liangyongxiang** [comment]
fixed: 079ef6af715f6125e91ca1d750c1e2ff328b1588
