### ISSUE TITLE
dev-util/wxformbuilder-3.6.0 fails to compile

### ISSUE THREAD

**Issue by atzengin** [gentoo-zh/overlay#429]
There are 2 issues with this package.

First, the directory name in the tar package is not what ebuild expects.
It expects wxformbuilder but the actual directory is wxFormBuilder-3.6.0

Second, if you work around the first one, is the error below;

> Unpacking source...
> Unpacking wxformbuilder-3.6.0.tar.gz to /var/tmp/portage/dev-util/wxformbuilder-3.6.0/work
> Source unpacked in /var/tmp/portage/dev-util/wxformbuilder-3.6.0/work
> Preparing source in /var/tmp/portage/dev-util/wxformbuilder-3.6.0/work/wxFormBuilder-3.6.0 ...
> ** No Premake script found!
> Source prepared.
> Configuring source in /var/tmp/portage/dev-util/wxformbuilder-3.6.0/work/wxFormBuilder-3.6.0 ...
> Source configured.
> Compiling source in /var/tmp/portage/dev-util/wxformbuilder-3.6.0/work/wxFormBuilder-3.6.0 ...
> make -j10 CONFIG=Release 
> make: *** No targets specified and no makefile found.  Stop.
> 
> ERROR: dev-util/wxformbuilder-3.6.0::gentoo-zh failed (compile phase):
> emake failed

**Comment by PaoJiao** [comment]
same here. 😞

**Comment by RevySR** [comment]
6611d4f The package is removed
