### ISSUE TITLE
2 font download link out-of-date

### ISSUE THREAD

**Issue by reppkchen** [gentoo-zh/overlay#437]
Hello, everyone!  I'm new to gentoo.

There are 2 font ebuilds' download links out-of-date.  They are:

- media-fonts/cwtex-q-fonts - Project has been moved from [google code](https://code.google.com/p/cwtex-q-fonts/) to [github](https://github.com/l10n-tw/cwtex-q-fonts).

- media-fonts/wangfonts -  SRC_URI might need to be changed into `https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/wangfonts/${P}.tar.gz`.

**Comment by CasperVector** [comment]
Should be fixed in 66db21ac; feel free to reopen if problem persists.
