### ISSUE TITLE
Error during eix-update: EAPI=4 is not supported

### ISSUE THREAD

**Issue by zainryan** [gentoo-zh/overlay#442]
When I executed eix-update, I encountered the following error.

ERROR: media-video/avplayer-9999::gentoo-zh failed (depend phase):
    EAPI=4 is not supported
  
  Call stack:
               ebuild.sh, line 611:  Called source '/var/lib/layman/gentoo-zh/media-video/avplayer/avplayer-9999.ebuild'
    avplayer-9999.ebuild, line   6:  Called inherit 'cmake-utils' 'git-2'
               ebuild.sh, line 307:  Called __qa_source '/usr/portage/eclass/cmake-utils.eclass'
               ebuild.sh, line 102:  Called source '/usr/portage/eclass/cmake-utils.eclass'
      cmake-utils.eclass, line  99:  Called die
  The specific snippet of code:
    	) die "EAPI=${EAPI:-0} is not supported" ;;
  
  If you need support, post the output of `emerge --info '=media-video/avplayer-9999::gentoo-zh'`,
  the complete build log and the output of `emerge -pqv '=media-video/avplayer-9999::gentoo-zh'`.
  Working directory: '/usr/lib64/python2.7/site-packages'
  S: '/avplayer-9999'

ebuild failed with status 1

**Comment by zainryan** [comment]
Attached the output of _**emerge --info '=media-video/avplayer-9999::gentoo-zh'**_ and **_emerge -pqv '=media-video/avplayer-9999::gentoo-zh'_**
[emerge-info.txt](https://github.com/microcai/gentoo-zh/files/1073338/emerge-info.txt)
[emerge-pqv.txt](https://github.com/microcai/gentoo-zh/files/1073339/emerge-pqv.txt)

**Comment by zainryan** [comment]
The source of avplayer-9999.ebuild is shown below.

_**EAPI=4**
inherit **cmake-utils** git-2_

_DESCRIPTION="avplayer is a p2p video downloader and player"
HOMEPAGE="http://avplayer.avplayer.org"
SRC_URI=""_

_EGIT_REPO_URI="https://github.com/avplayer/avplayer.git"_

_LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64 ~x86"_

_DEPEND=">=dev-libs/boost-1.49[threads,static-libs]
		dev-libs/openssl 
		media-libs/libsdl"
RDEPEND="${DEPEND}"_

As you see, it set EAPI = 4 and inherit cmake-utils.eclass.
According to /usr/portage/eclass/cmake-utils.eclass, EAPI cannot be set to 4. Below is its code snippet.

  ****96 case ${EAPI} in                                                                                                                                          
  97         5) : ${CMAKE_WARN_UNUSED_CLI:=no} ;;                                                                                                             
  98         6) : ${CMAKE_WARN_UNUSED_CLI:=yes} ;;                                                                                                            
  99         *) die "EAPI=${EAPI:-0} is not supported" ;;                                                                                                     
 100 esac****

**Comment by vizv** [comment]
The following ebuilds are also related to this issue:

```
app-i18n/fcitx-fbterm/fcitx-fbterm-9999.ebuild
app-i18n/fcitx-rime/fcitx-rime-9999.ebuild
app-i18n/fcitx-table-extra/fcitx-table-extra-9999.ebuild
app-i18n/ibus-googlepinyin/ibus-googlepinyin-0.1.2.ebuild
media-video/avplayer/avplayer-9999.ebuild
sys-apps/e4rat/e4rat-0.2.1.ebuild
x11-wm/compiz/compiz-0.9.99.20130608170409.ebuild
```

**Comment by vizv** [comment]
I just confirmed the error will be gone if change `EAPI=4` to `EAPI=5` for the seven ebuilds listed above, however I didn't test if the package is actually going to build...

**Comment by zainryan** [comment]
According to my experience, changing EAPI from 4 to 5 won't cause build error for most of the time. 
Also, there is a presentation at Gentoo MiniConf 2014 which discloses the difference of EAPI5 & EAPI4. 
(page 6 at https://www.linuxdays.cz/2014/video/Ulrich_Muller-EAPI6.pdf). From this presentation, we can see EAPI5 is actually an extended version of EAPI4.

**Comment by vizv** [comment]
I'll let maintainer decide, maybe you can talk to microcai.

**Comment by vizv** [comment]
I don't use these packages now, so here is my temporary fix to get rid of the errors.

```diff
diff --git a/app-i18n/fcitx-fbterm/fcitx-fbterm-9999.ebuild b/app-i18n/fcitx-fbterm/fcitx-fbterm-9999.ebuild
index d8fe66a4..f6680f00 100644
--- a/app-i18n/fcitx-fbterm/fcitx-fbterm-9999.ebuild
+++ b/app-i18n/fcitx-fbterm/fcitx-fbterm-9999.ebuild
@@ -2,7 +2,7 @@
 # Distributed under the terms of the GNU General Public License v2
 # $Header: $
 
-EAPI="4"
+EAPI=5
 EGIT_REPO_URI="https://github.com/fcitx/fcitx-fbterm.git"
 
 inherit git-2 cmake-utils
diff --git a/app-i18n/fcitx-rime/fcitx-rime-9999.ebuild b/app-i18n/fcitx-rime/fcitx-rime-9999.ebuild
index 59e47bfe..d7ca4eac 100644
--- a/app-i18n/fcitx-rime/fcitx-rime-9999.ebuild
+++ b/app-i18n/fcitx-rime/fcitx-rime-9999.ebuild
@@ -2,7 +2,7 @@
 # Distributed under the terms of the GNU General Public License v2
 # $Header: $
 
-EAPI=4
+EAPI=5
 
 inherit cmake-utils git-2
 
diff --git a/app-i18n/fcitx-table-extra/fcitx-table-extra-9999.ebuild b/app-i18n/fcitx-table-extra/fcitx-table-extra-9999.ebuild
index 5e545cce..901a5b00 100644
--- a/app-i18n/fcitx-table-extra/fcitx-table-extra-9999.ebuild
+++ b/app-i18n/fcitx-table-extra/fcitx-table-extra-9999.ebuild
@@ -2,7 +2,7 @@
 # Distributed under the terms of the GNU General Public License v2
 # $Header: $
 
-EAPI="4"
+EAPI=5
 
 if [[ ${PV} == "9999" ]]; then
 	EGIT_REPO_URI="https://github.com/fcitx/fcitx-table-extra.git"
diff --git a/app-i18n/ibus-googlepinyin/ibus-googlepinyin-0.1.2.ebuild b/app-i18n/ibus-googlepinyin/ibus-googlepinyin-0.1.2.ebuild
index b6893cc2..c5516420 100644
--- a/app-i18n/ibus-googlepinyin/ibus-googlepinyin-0.1.2.ebuild
+++ b/app-i18n/ibus-googlepinyin/ibus-googlepinyin-0.1.2.ebuild
@@ -2,7 +2,7 @@
 # Distributed under the terms of the GNU General Public License v2
 # $Header: $
 
-EAPI=4
+EAPI=5
 
 HOMEPAGE="http://libgooglepinyin.googlecode.com/"
 
diff --git a/media-video/avplayer/avplayer-9999.ebuild b/media-video/avplayer/avplayer-9999.ebuild
index b1b6aef6..1e9c55e9 100644
--- a/media-video/avplayer/avplayer-9999.ebuild
+++ b/media-video/avplayer/avplayer-9999.ebuild
@@ -2,7 +2,7 @@
 # Distributed under the terms of the GNU General Public License v2
 # $Header: $
 
-EAPI=4
+EAPI=5
 inherit cmake-utils git-2
 
 DESCRIPTION="avplayer is a p2p video downloader and player"
diff --git a/sys-apps/e4rat/e4rat-0.2.1.ebuild b/sys-apps/e4rat/e4rat-0.2.1.ebuild
index c837e02d..244cd9f5 100644
--- a/sys-apps/e4rat/e4rat-0.2.1.ebuild
+++ b/sys-apps/e4rat/e4rat-0.2.1.ebuild
@@ -2,7 +2,7 @@
 # Distributed under the terms of the GNU General Public License v2
 # $Header: $
 
-EAPI=4
+EAPI=5
 
 inherit cmake-utils
 
diff --git a/x11-wm/compiz/compiz-0.9.99.20130608170409.ebuild b/x11-wm/compiz/compiz-0.9.99.20130608170409.ebuild
index 370e35d4..2f22c97a 100644
--- a/x11-wm/compiz/compiz-0.9.99.20130608170409.ebuild
+++ b/x11-wm/compiz/compiz-0.9.99.20130608170409.ebuild
@@ -2,7 +2,7 @@
 # Distributed under the terms of the GNU General Public License v2
 # $Header: $
 
-EAPI=4
+EAPI=5
 
 inherit versionator
 
```

**Comment by zainryan** [comment]
Dear @microcai, may you have a look at this issue?

**Comment by CasperVector** [comment]
Perhaps we can simply follow #284 and apply the patch above if nobody objects in several days?

**Comment by CasperVector** [comment]
Patch applied.
