### ISSUE TITLE
Please update dev-php/solr to php-ext-pecl-r3 eclass

### ISSUE THREAD

**Issue by ghost** [gentoo-zh/overlay#449]
Hello,

The php-ext-pecl-r2 eclass will be removed in a month or two as the last two packages in main Gentoo repository are removed.

I suggest you take a few moments and upgrade dev-php/pecl-solr to EAPI=6 and php-ext-pecl-r3

Thanks.

Brian
grknight@gentoo.org
PHP team member

**Comment by zackhzb** [comment]
Already fixed in b7098b45420d1dc4b8863c02b61c83c4152d323d. Please close.
