### ISSUE TITLE
The dependency of dbus can be removed for sogoupinyin

### ISSUE THREAD

**Issue by lizhuohua** [gentoo-zh/overlay#451]
According to the latest commit of fcitx, the "dbus" USE flag has been removed:
`app-i18n/fcitx: Delete "dbus" USE flag and unconditionally enable support for DBus. `
See [here](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=94ededead382d8d387b32bf4d1d49357f0335e4e)

So the dependency of dbus shoud also be removed:
RDEPEND=">=app-i18n/fcitx-4.2.8[qt4,X,~~dbus~~]

Otherwise, there will be a dependency conflict while updating fcitx.

**Comment by zaynr** [comment]
# hua shen niu b

**Comment by lizhuohua** [comment]
# @zaynr wo zui zha
