### ISSUE TITLE
visual-studio-code gives "spawn EACCESS" error when using "Find in files"

### ISSUE THREAD

**Issue by fpemud** [gentoo-zh/overlay#463]
Step:
1. Click menu "Edit" -> "Find in files"
2. Input some text in Search textbox
3. Press ENTER
4. Red error "spawn EACCESS" appears

**Comment by microcai** [comment]
@fpemud upstream bug should be reported upstream.

**Comment by fpemud** [comment]
I don't know but I guess it is not an upstream bug but a bug in ebuild.
I think upstream bug should affect all people.

**Comment by microcai** [comment]
@fpemud emm

**Comment by microcai** [comment]
fix upstream
