### ISSUE TITLE
emerge media-sound/netease-cloud-music-1.1.0出错

### ISSUE THREAD

**Issue by wgjak47** [gentoo-zh/overlay#467]
```
chmod: cannot access '/var/tmp/portage/media-sound/netease-cloud-music-1.1.0/image//usr/lib64/netease-cloud-music/lib/*': No such file or directory
```

但是直接执行出错的命令却没有问题：
```
sudo chmod 777 /var/tmp/portage/media-sound/netease-cloud-music-1.1.0/image//usr/lib64/netease-cloud-music/lib/*
```

**Comment by lizhuohua** [comment]
同样的问题
应该是因为fperms不支持通配符，而ebuild里这句却这么用了：
`fperms 0755 /usr/$(get_libdir)/${PN}/lib/*`
奇怪的是好像并不是所有人都会出错

**Comment by microcai** [comment]
@lizhuohua 这个 通配符会被 shell 展开的. 除非 shell 找不到文件,就会原样传给命令

**Comment by wgjak47** [comment]
我的portage版本是2.3.13-r1，难道根这个有关系吗？

**Comment by lizhuohua** [comment]
网上能搜到关于fperms和wildcard的问题，比如[这里](https://github.com/aegypius/overlay/issues/65)，最终解决是用了fperms -R：

> I think fperms doesn't work well with wildcards, I just replace fperms lines @steffenweber mentioned before with fperms -R without wildcard, and that works fine.

**Comment by wgjak47** [comment]
我把*去掉之后，就没有问题了。

**Comment by OwenChia** [comment]
lib 这个目录下需要全部 0755 的权限吗？so 文件似乎不用 x 权限吧？我看了下我的 0644 可以正常运行。

我自己的 src_install 是这样的（安装包是网易云音乐网站上的）：
```
src_install() {
        insinto /
        doins -r ${S}/usr/

        dodir /usr/bin
        exeinto /usr/bin
        doexe ${S}/usr/bin/netease-cloud-music
}
```

**Comment by lizhuohua** [comment]
@OwenChia 嗯，so文件应该只是习惯上用755，其实644就够了
