### ISSUE TITLE
Sogou pinyin need update

### ISSUE THREAD

**Issue by gentoolovers** [gentoo-zh/overlay#475]
Sogou pinyin dpends on  the library of libQtWebKit.so.4,but the PyQt4 had remved the webkit use.

**Comment by microcai** [comment]
@gentoolovers python is like shit. use python when u want to eat shit.

**Comment by gentoolovers** [comment]
@microcai  You can not represent others.

**Comment by microcai** [comment]
@gentoolovers PYTHON is SHIT. SHIT. SHIT. are you happy now ?
