### ISSUE TITLE
emerge media-sound/netease-cloud-music-1.1.0 安装成功,运行失败

### ISSUE THREAD

**Issue by liulanghaitun** [gentoo-zh/overlay#478]
安装成功后运行出现错误:
netease-cloud-music: error while loading shared libraries: libqcef.so.1: cannot open shared object file: No such file or directory

编译过程中出现的提示:
scanelf: rpath_security_checks(): Security problem with relative DT_RPATH '.:$ORIGIN' in /var/tmp/portage/media-sound/netease-cloud-musi
c-1.1.0/image/usr/lib64/netease-cloud-music/lib/libqcef.so.1.1.2                                                                        
scanelf: rpath_security_checks(): Security problem with relative DT_RPATH '.:$ORIGIN' in /var/tmp/portage/media-sound/netease-cloud-musi
c-1.1.0/image/usr/lib64/netease-cloud-music/lib/libqcef.so.1.1.2

请问一下gentoo需要安装那个包,包含libqcef.so.1这个库.

**Comment by tolbkni** [comment]
试试安装 dev-qt/qcef 这个包

**Comment by liulanghaitun** [comment]
安装qcef之后,安装成功,但是运行是报错:

[0328/203357.773491:ERROR:icu_util.cc(173)] Invalid file descriptor to ICU data received.
[0328/203357.773567:FATAL:content_main_runner.cc(620)] Check failed: base::i18n::InitializeICU(). 
#0 0x7ff39a848536 <unknown>
#1 0x7ff39a866ad2 <unknown>
#2 0x7ff39a78b652 <unknown>
#3 0x7ff39bb16784 <unknown>
#4 0x7ff39a7ad07f <unknown>
#5 0x7ff39a7ad231 <unknown>
#6 0x7ff39951ec7e cef_initialize
#7 0x7ff3a691e194 <unknown>
#8 0x7ff3a68ee9fa QCefInit()
#9 0x55d240e742de <unknown>
#10 0x7ff3a2eb2541 __libc_start_main
#11 0x55d240e763aa <unknown>

请问该如何修复这个问题?

**Comment by liulanghaitun** [comment]
我把ebuild安装文件里面替换成下面这个就成功了:
src_install() {
        insinto /
        doins -r ${S}/usr/

        dodir /usr/bin
        exeinto /usr/bin
        doexe ${S}/usr/bin/netease-cloud-music
}
