### ISSUE TITLE
The SRC_URI of dev-libs/lunar-date is out-of-date

### ISSUE THREAD

**Issue by Universebenzene** [gentoo-zh/overlay#482]
The old URI http://liblunar.googlecode.com/ is no longer exist. The new upstream should be https://github.com/yetist/lunar-date/

**Comment by Universebenzene** [comment]
好像是我英文太差了菊苣们不屑于看……想装贵仓库的dev-libs/lunar-date但是ebuild里的SRC_URI好像不存在了，改成 https://github.com/yetist/lunar-date/releases 是不是可以……

**Comment by microcai** [comment]
@Universebenzene 新的地址多少

**Comment by Universebenzene** [comment]
@microcai 目前最新版本是2.4.2，地址就在github上，https://github.com/yetist/lunar-date/archive/v2.4.2.tar.gz
