### ISSUE TITLE
不知道是否有可能把 app-i18n/fcitx-sogoupinyin    的源，从deepin 更新成搜狗官方版？

### ISSUE THREAD

**Issue by ghost** [gentoo-zh/overlay#483]
不知道是否有可能把 app-i18n/fcitx-sogoupinyin    的源，从deepin 更新成搜狗官方版（与Ubuntu Kylin团队合作开发的版本， 发布日期：2017-11-02）

软件地址：https://pinyin.sogou.com/linux/?r=pinyin    

32bit 下载地址：https://pinyin.sogou.com/linux/download.php?f=linux&bit=32

64bit 下载地址：https://pinyin.sogou.com/linux/download.php?f=linux&bit=64

**Comment by microcai** [comment]
@availa 开源不

**Comment by ghost** [comment]
不太清楚是否开源，下载下来是个 .deb的包。

也许可以参照 dev-java/oracle-jdk-bin  的方式，让用户去网站下载，放到 /usr/portage/distfiles/  中，再安装。

**Comment by ghost** [comment]
找到了，部分开源

源代码位置：

https://github.com/sogoupinyin/


fcitx-qimpanel: 面板独立成为一个项目
https://github.com/sogoupinyin/fcitx-qimpanel
fcitx-fullwidthchar-enhance: 全角字符行为增强模块
https://github.com/sogoupinyin/fcitx-fullwidthchar-enhance
fcitx-punc-ng: 标点处理模块
https://github.com/sogoupinyin/fcitx-punc-ng
fcitx-autoeng-ng: 快速输入处理模块
https://github.com/sogoupinyin/fcitx-autoeng-ng

**Comment by microcai** [comment]
@availa 那不是他的东西

**Comment by microcai** [comment]
那只是把 fcitx  fork 了一下，真正的 sougoupinyin 没开源。没有代码怎么更新？

**Comment by ghost** [comment]
直接拆解 deb二进制包，然后安装，不知道可行不？看到 官方源中，www-client/google-chrome  就是拆解的deb包，把二进制文件安装的，不是本地编译的。只是不知道这样是不是会违反 一些协议或者其他的一些要求

**Comment by ykla** [comment]
搜狗怎么可能开源

**Comment by liangyongxiang** [comment]
app-i18n/fcitx-sogoupinyin drop: https://github.com/microcai/gentoo-zh/commit/a053d1559a89602eea13e823258b627fd354d67f
