### ISSUE TITLE
emerge =media-sound/netease-cloud-music-1.1.0 error

### ISSUE THREAD

**Issue by gorf** [gentoo-zh/overlay#484]
>>> Install netease-cloud-music-1.1.0 into /var/tmp/portage/media-sound/netease-cloud-music-1.1.0/image/ category media-sound
chmod: cannot access '/var/tmp/portage/media-sound/netease-cloud-music-1.1.0/image//usr/lib64/netease-cloud-music/lib/*': No such file or directory
 * ERROR: media-sound/netease-cloud-music-1.1.0::gentoo-zh failed (install phase):
 *   fperms failed
 * 
 * If you need support, post the output of `emerge --info '=media-sound/netease-cloud-music-1.1.0::gentoo-zh'`,
 * the complete build log and the output of `emerge -pqv '=media-sound/netease-cloud-music-1.1.0::gentoo-zh'`.
 * The complete build log is located at '/var/tmp/portage/media-sound/netease-cloud-music-1.1.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-sound/netease-cloud-music-1.1.0/temp/environment'.
 * Working directory: '/var/tmp/portage/media-sound/netease-cloud-music-1.1.0/work'
 * S: '/var/tmp/portage/media-sound/netease-cloud-music-1.1.0/work'

**Comment by lizhuohua** [comment]
see #467
