### ISSUE TITLE
sogou输入法更新2.2后出现缺少libqtwebkit.so.4

### ISSUE THREAD

**Issue by arklee** [gentoo-zh/overlay#486]
运行sogou-qimpanel出现sogou-qimpanel: error while loading shared libraries: libQtWebKit.so.4: cannot open shared object file: No such file or directory
有一段时间没用sogou了，最近发现更新了2.2,但安装后不能用

**Comment by wgjak47** [comment]
+1

**Comment by VZIKL** [comment]
gentoo 上游删掉了qt4 所以libqtwebkit那个文件没了  只能让sogoulinux团队更新QT版本了吧:D

**Comment by wgjak47** [comment]
我看arch那边似乎是提供了qiwebkit bin的包？

**Comment by Mddct** [comment]
现在是怎么样解决的？

**Comment by microcai** [comment]
@Mddct 升级 sogou 吧，用啥 qt4 , 该用 qt5 了。

**Comment by microcai** [comment]
@Mddct 可以试试fcitx5

**Comment by Mddct** [comment]
直接从ubuntu 中拿了个libQtWebKit.so.4  libQtWebKit.so.4.10 libjpeg.so.8  libjpeg.so.8.0.2 暂时解决了。

**Comment by liangyongxiang** [comment]
drop in : a053d1559a89602eea13e823258b627fd354d67f
