### ISSUE TITLE
media-sound/cantata的ebuild有錯誤:

### ISSUE THREAD

**Issue by SleepyMario** [gentoo-zh/overlay#488]
eix的output如下:

[4] "gentoo-zh" /usr/local/portage/gentoo-zh (cache: parse|ebuild*#metadata-md5#metadata-flat#assign)
     Reading category 104|174 ( 59): media-sound... * ERROR: media-sound/cantata-1.3.4-r1::gentoo-zh failed (depend phase):
 *   kde4-base.eclass could not be found by inherit()
 * 
 * Call stack:
 *                 ebuild.sh, line 620:  Called source '/usr/local/portage/gentoo-zh/media-sound/cantata/cantata-1.3.4-r1.ebuild'
 *   cantata-1.3.4-r1.ebuild, line   9:  Called inherit 'kde4-base' 'l10n'
 *                 ebuild.sh, line 293:  Called die
 * The specific snippet of code:
 *   		[[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
 * 
 * If you need support, post the output of `emerge --info '=media-sound/cantata-1.3.4-r1::gentoo-zh'`,
 * the complete build log and the output of `emerge -pqv '=media-sound/cantata-1.3.4-r1::gentoo-zh'`.
 * Working directory: '/usr/lib64/python2.7/site-packages'
 * S: '/cantata-1.3.4'

**Comment by microcai** [comment]
官方源有新版了， delete 老版本。
