### ISSUE TITLE
fcitx 出现EAPI=5错误

### ISSUE THREAD

**Issue by jweiquan** [gentoo-zh/overlay#501]
app-i18n/fcitx

**Comment by jweiquan** [comment]
Calculating dependencies / * ERROR: app-i18n/fcitx-4.2.9.6::gentoo-zh failed (depend phase):
 *   EAPI=5 is not supported
 * 
 * Call stack:
 *               ebuild.sh, line 635:  Called source '/var/lib/layman/gentoo-zh/app-i18n/fcitx/fcitx-4.2.9.6.ebuild'
 *    fcitx-4.2.9.6.ebuild, line   7:  Called inherit 'eutils' 'gnome2-utils' 'fdo-mime' 'readme.gentoo' 'cmake-multilib'
 *               ebuild.sh, line 326:  Called __qa_source '/usr/portage/eclass/cmake-multilib.eclass'
 *               ebuild.sh, line 111:  Called source '/usr/portage/eclass/cmake-multilib.eclass'
 *   cmake-multilib.eclass, line  24:  Called die
 * The specific snippet of code:
 *   	*) die "EAPI=${EAPI} is not supported" ;;
 * 
 * If you need support, post the output of `emerge --info '=app-i18n/fcitx-4.2.9.6::gentoo-zh'`,
 * the complete build log and the output of `emerge -pqv '=app-i18n/fcitx-4.2.9.6::gentoo-zh'`.
 * Working directory: '/usr/lib64/python3.6/site-packages'
 * S: '/var/tmp/portage/app-i18n/fcitx-4.2.9.6/work/fcitx-4.2.9.6'

**Comment by jweiquan** [comment]
`Calculating dependencies / * ERROR: app-i18n/fcitx-4.2.9.6::gentoo-zh failed (depend phase):
 *   EAPI=5 is not supported
 * 
 * Call stack:
 *               ebuild.sh, line 635:  Called source '/var/lib/layman/gentoo-zh/app-i18n/fcitx/fcitx-4.2.9.6.ebuild'
 *    fcitx-4.2.9.6.ebuild, line   7:  Called inherit 'eutils' 'gnome2-utils' 'fdo-mime' 'readme.gentoo' 'cmake-multilib'
 *               ebuild.sh, line 326:  Called __qa_source '/usr/portage/eclass/cmake-multilib.eclass'
 *               ebuild.sh, line 111:  Called source '/usr/portage/eclass/cmake-multilib.eclass'
 *   cmake-multilib.eclass, line  24:  Called die
 * The specific snippet of code:
 *   	*) die "EAPI=${EAPI} is not supported" ;;
 * 
 * If you need support, post the output of `emerge --info '=app-i18n/fcitx-4.2.9.6::gentoo-zh'`,
 * the complete build log and the output of `emerge -pqv '=app-i18n/fcitx-4.2.9.6::gentoo-zh'`.
 * Working directory: '/usr/lib64/python3.6/site-packages'
 * S: '/var/tmp/portage/app-i18n/fcitx-4.2.9.6/work/fcitx-4.2.9.6'
`

**Comment by microcai** [comment]
@jweiquan 好，马上修
