### ISSUE TITLE
安装deepin-wine-wechat的时候，deepin-wine-helper安装不成功

### ISSUE THREAD

**Issue by liangyongxiang** [gentoo-zh/overlay#507]
```
 # emerge -av net-im/deepin-wine-wechat
......
Calculating dependencies... done!
[ebuild  N    ~] app-emulation/deepin-wine-helper-1.0.27::gentoo-zh  700 KiB
[ebuild  N    ~] net-im/deepin-wine-wechat-2.6.0.40.1::gentoo-zh  44,686 KiB
......
>>> Downloading 'http://packages.deepin.com/deepin/pool/non-free/d/deepin-wine-helper/deepin-wine-helper_1.0deepin27_i386.deb'
--2019-02-01 15:52:52--  http://packages.deepin.com/deepin/pool/non-free/d/deepin-wine-helper/deepin-wine-helper_1.0deepin27_i386.deb
Resolving packages.deepin.com... 202.141.160.114
Connecting to packages.deepin.com|202.141.160.114|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-02-01 15:52:52 ERROR 404: Not Found.
```
我去deepin看了，现在的版本是：http://packages.deepin.com/deepin/pool/non-free/d/deepin-wine-helper/deepin-wine-helper_1.2deepin0_i386.deb
~

**Comment by wgjak47** [comment]
从deepin的overlay搞了一份新的过来了，你试试

**Comment by liangyongxiang** [comment]
嗯，没看到相关的commit呢。 @wgjak47

**Comment by wgjak47** [comment]
@liangyongxiang 囧，push到我自己的repo去了...

**Comment by microcai** [comment]
@wgjak47 要不要 push 回来？

**Comment by liangyongxiang** [comment]
还是不行的。deepin的overlay也是不够新。
它去这个地址下载：
http://packages.deepin.com/deepin/pool/non-free/d/deepin-wine-helper/deepin-wine-helper_1.1deepin12_i386.deb

这里有两个问题，版本不对，现在只有1.2了。链接的格式也不对。deepin12现在是deepin0了。

**Comment by liangyongxiang** [comment]
我尝试在本地自己建立overlay，修改了ebuild文件，可以安装了。但是启动还是失败。
我去看了archlinux的对应软件包，他们做了更多工作。
但是我不懂怎么把archlinux的package修改成为gentoo的。

**Comment by zhtengw** [comment]
@liangyongxiang 实际问题是现在deepin-wine在gentoo下运行会产生段错误，因为我没在Linux下用QQ微信，所以发现得晚，现在也不知道是哪次更新，什么原因导致的了。

**Comment by zhtengw** [comment]
deepin-overlay中deepin-wine的组件已经齐全的了，并没有缺少

**Comment by liangyongxiang** [comment]
@zhtengw 嗯嗯，那留着issue，等修复了再关闭？

**Comment by zhtengw** [comment]
今天仔细观察了下，deepin-wine 出现段错误后，dmesg记录是：
```
[136968.719683] traps: wine[45932] general protection ip:7eb39785 sp:ffa42684 error:0 in libxcb.so.1.1.0[7eb38000+16000]
```
根据这个搜到了gentoo Bugzilla的记录，说是libxcb的编译优化等级太高导致teamviewer.exe运行出现段错误，将cflags设为-O1就可以恢复正常。我这边用CFLAGS="-march=native -O1 -pipe" 重新编译安装了x11-libs/libxcb和x11-libs/libX11就可以正常运行deepin-wine的软件了。

（PS：重新安装libxcb后，dmesg记录到
```
[138213.717073] traps: wine[41274] general protection ip:7edc78de sp:ffb5e154 error:0 in libX11.so.6.3.0[7eda0000+8d000]
```
所以我又用O1安装了libX11）

您可以试试在你的机子上可不可以解决。
参考资料：
1、https://forums.gentoo.org/viewtopic-t-1071116.html?sid=f5c72bf9281df68c360808e5d434f2ad
2、https://bugs.gentoo.org/616402
3、https://community.teamviewer.com/t5/Linux/Teamviewer-Linux-Segfault-in-wine-gentoo/td-p/16979
4、https://bbs.archlinux.org/viewtopic.php?id=213238

**Comment by liangyongxiang** [comment]
按照你的方式做了之后，dmesg里面的错误解决了。
但是我遇到了新的问题。我尝试QQ和Wechat都是一样
```
 X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x0
  Serial number of failed request:  10
  Current serial number in output stream:  10
```
我注意到你提过相关的问题：https://bbs.deepin.org/forum.php?mod=viewthread&tid=135663
好像没看到解决办法。
@zhtengw

**Comment by zhtengw** [comment]
是的，因为deepin-wine闭源，这个X Window的错误只能深度团队去解决，他们不打算做就没办法了。目前只能在gnome dde桌面环境运行

**Comment by liangyongxiang** [comment]
嗯嗯，谢谢啦。
