### ISSUE TITLE
Add v2ray-4.x

### ISSUE THREAD

**Issue by GreatEmerald** [gentoo-zh/overlay#508]
v2ray now has been updated to version 4, which among other things includes a new config file format. It would be nice if we could have an ebuild for that.

**Comment by danielliulihua** [comment]
https://data.gpo.zugaina.org/gig/net-proxy/v2ray/

**Comment by RevySR** [comment]
Now, this repo has [net-proxy/v2ray-bin](https://github.com/microcai/gentoo-zh/tree/master/net-proxy/v2ray-bin).
