### ISSUE TITLE
librime 默认产生包含输入信息的 INFO 级别日志问题

### ISSUE THREAD

**Issue by OwenChia** [gentoo-zh/overlay#509]
日志文件 /tmp/rime.fcitx-rime.INFO

内容摘抄如下
```
...
I0224 01:08:53.890812  8381 user_dictionary.cc:219] forward scanning for 'cun en '.
I0224 01:08:53.890826  8381 user_dictionary.cc:196] prefix: 'cun ', syll_id: 85, num_spellings: 1
I0224 01:08:53.890836  8381 user_dictionary.cc:217] edge: [1, 2)
I0224 01:08:53.890843  8381 user_dictionary.cc:219] forward scanning for 'cun eng '.
I0224 01:08:53.890857  8381 user_dictionary.cc:196] prefix: 'cun ', syll_id: 86, num_spellings: 1
I0224 01:08:53.890867  8381 user_dictionary.cc:217] edge: [1, 2)
I0224 01:08:53.890875  8381 user_dictionary.cc:219] forward scanning for 'cun er '.
I0224 01:08:53.890889  8381 user_dictionary.cc:196] prefix: '', syll_id: 56, num_spellings: 1
I0224 01:08:53.890898  8381 user_dictionary.cc:217] edge: [0, 1)
I0224 01:08:53.890906  8381 user_dictionary.cc:219] forward scanning for 'cuo '.
I0224 01:08:53.890938  8381 menu.cc:22] 1 translations added.
I0224 01:08:53.890954  8381 dictionary.cc:95] creating temporary dict entry '測試'.
I0224 01:08:53.890969  8381 script_translator.cc:483] phrase '測試', code length: 1
I0224 01:08:53.890998  8381 dictionary.cc:95] creating temporary dict entry '廁所'.
I0224 01:08:53.891011  8381 script_translator.cc:483] phrase '廁所', code length: 1
I0224 01:08:53.891062  8381 menu.cc:30] preparing 1 candidates.
I0224 01:08:53.891074  8381 dictionary.cc:95] creating temporary dict entry '測算'.
I0224 01:08:53.891096  8381 script_translator.cc:483] phrase '測算', code length: 1
I0224 01:08:53.891052  8381 engine.cc:159] composition: {abc}ces=>测试
I0224 01:08:53.891111  8381 key_binding_processor_impl.h:49] action key accepted: BackSpace
I0224 01:08:53.891134  8381 menu.cc:30] preparing 5 candidates.
I0224 01:08:53.891140  8381 dictionary.cc:95] creating temporary dict entry '測速'.
I0224 01:08:53.891152  8381 script_translator.cc:483] phrase '測速', code length: 1
I0224 01:08:53.891166  8381 dictionary.cc:95] creating temporary dict entry '側身'.
...
```

通过关键字搜索，定位到产生日志的是 librime

经与上游沟通得知
> librime 中使用了 glog 的 DLOG 来输出日志
> glog 中的 DLOG 是 debug 宏，在 release 不输出
> 其它平台没有在 release 下输出 debug 日志的问题

虽然出问题的包是 Gentoo 在维护，但考虑到这里的用户使用输入法的概率较大，更有可能遇到同样的问题，于是在这里报告了。

通过翻阅文档并做了几个实验，（连蒙带猜）确认了以下几点
 - glog 的 LOG 默认级别是 INFO （minloglevel = 0）

 - DLOG 只有在` cmake -DCMAKE_BUILD_TYPE=Release` 或 `g++ -DNDEBUG` 时不输出

 - gentoo 默认的 CMAKE_BUILD_TYPE 值是 [Gentoo](https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/cmake-utils.eclass#n45)

- 在满足 `${CMAKE_BUILD_TYPE} = Gentoo` 和 `! has debug ${IUSE//+} || ! use debug` 的条件下
执行 [append-cppflags -DNDEBUG](https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/cmake-utils.eclass#n537)

- 在 ebuild 的 mycmakeargs 中添加` -DCMAKE_EXPORT_COMPILE_COMMANDS=ON` 参数，生成的 compile_commands.json 文件中无 `-DNDEBUG` 字样

有人知道这里的 `-DNDEBUG` 为什么没有被添加上吗？是我遗漏了什么还是？

目前的 workaround:
在 mycmakeargs 中添加参数 -DENABLE_LOGGING=OFF

**Comment by microcai** [comment]
@OwenChia 这个是属于 google 自己的bug 吧。

**Comment by OwenChia** [comment]
> @OwenChia 这个是属于 google 自己的bug 吧。

不懂……为什么说是 个哦哦过了

**Comment by OwenChia** [comment]
> @OwenChia 这个是属于 google 自己的bug 吧。

不懂……为什么说是 google 的 bug ？

我的理解（错了请纠正）是，因为某些原因，通过 `append-cppflags -DNDEBUG`添加的 flag 被 cmake 忽略了，所以导致了这样的问题。

另：单独解压 librime 源码并执行
```
cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
```
后得到的 compile_commands.json 文件中存在 `-DNDEBUG`

**Comment by wgjak47** [comment]
@OwenChia 应该是ebuild哪里要加个-D CMAKE_BUILD_TYPE=release？

**Comment by OwenChia** [comment]
> @OwenChia 应该是ebuild哪里要加个-D CMAKE_BUILD_TYPE=release？

我添加过这个，但还是会输出日志，不知道是哪里出问题了（环境不干净？漏掉了步骤？）

试过两种方法添加：
- 在 src_configure 中 cmake-utils_src_configure 前添加 local CMAKE_BUILD_TYPE=Release
- 在 mycmakeargs 中添加 -DCMAKE_BUILD_TYPE=Release 

步骤是：
1. 添加参数，重新安装
2. 退出输入法，删掉日志
3. 启动输入法打字，检查日志是否出现

**Comment by OwenChia** [comment]
@dlan17 你有遇到这样的情况吗？
