### ISSUE TITLE
wps office无法安装

### ISSUE THREAD

**Issue by mintiandeniwo** [gentoo-zh/overlay#529]
卡在了一个依赖:media-libs/libuninameslist-20140731.
尝试安装时报错:HTTP request sent, awaiting response... 404 Not Found

>>> Downloading 'https://github.com/fontforge/libuninameslist/archive/0.4.20140731.tar.gz'
--2019-09-05 16:47:44--  https://github.com/fontforge/libuninameslist/archive/0.4.20140731.tar.gz
Resolving github.com... 140.82.118.4
Connecting to github.com|140.82.118.4|:443... connected.
Unable to establish SSL connection.
!!! Couldn't download 'libuninameslist-0.4.20140731.tar.gz'. Aborting.
 * Fetch failed for 'media-libs/libuninameslist-20140731', Log file:
 *  '/var/tmp/portage/media-libs/libuninameslist-20140731/temp/build.log'

**Comment by tlze** [comment]
你那里github可能访问有问题（如被墙了）。我测试没问题。
如果有方法，修改/etc/gitconfig，内容如下：
[http]
	proxy = socks5://127.0.0.1:1080

附测试日志
[compile.log](https://github.com/microcai/gentoo-zh/files/3578869/compile.log)

**Comment by mintiandeniwo** [comment]
>>> Emerging (1 of 1) app-office/wps-office-11.1.0.8722::gentoo-zh
Refetching... File renamed to '/var/cache/distfiles/wps-office_11.1.0.8722_amd64.deb._checksum_failure_.ljgst0iq'

>>> Downloading 'http://kdl.cc.ksosoft.com/wps-community/download/8722/wps-office_11.1.0.8722_amd64.deb'
--2019-09-05 22:35:28--  http://kdl.cc.ksosoft.com/wps-community/download/8722/wps-office_11.1.0.8722_amd64.deb
Resolving kdl.cc.ksosoft.com... 209.177.81.202, 106.48.12.141
Connecting to kdl.cc.ksosoft.com|209.177.81.202|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 259062038 (247M) [application/octet-stream]
Saving to: ‘/var/cache/distfiles/wps-office_11.1.0.8722_amd64.deb.__download__’

/var/cache/distfile 100%[===================>] 247.06M  2.19MB/s    in 73s     

2019-09-05 22:36:42 (3.36 MB/s) - ‘/var/cache/distfiles/wps-office_11.1.0.8722_amd64.deb.__download__’ saved [259062038/259062038]

!!! Fetched file: wps-office_11.1.0.8722_amd64.deb VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      259062038
!!! Expected: 259160398
Refetching... File renamed to '/var/cache/distfiles/wps-office_11.1.0.8722_amd64.deb._checksum_failure_.ljgst0iq'

!!! Couldn't download 'wps-office_11.1.0.8722_amd64.deb'. Aborting.
 * Fetch failed for 'app-office/wps-office-11.1.0.8722', Log file:
 *  '/var/tmp/portage/app-office/wps-office-11.1.0.8722/temp/build.log'

>>> Failed to emerge app-office/wps-office-11.1.0.8722, Log file:

**Comment by tlze** [comment]
这个不知道谁的锅，的确下载后是检验不通过，文件大小不对。
试试从下面链接下载后放到distfiles（这个是我上传的）
https://send.firefox.com/download/75f939e443e208ff/#Kl5D95172rZMvxPyKsbY5w

**Comment by Universebenzene** [comment]
@tlze 这个我明确讲是WPS上游的锅。我是维护AUR上wps的，上回WPS一点招呼都没打就把上游包给改了，网页上的散列值也不改，莫名其妙。只能说辣鸡金山。让蔡博士把散列值更新一下就是了

**Comment by mintiandeniwo** [comment]
>>> Verifying ebuild manifests

>>> Emerging (1 of 1) media-fonts/wps-office-fonts-1.0::gentoo-zh
 * wps-office-fonts_1.0_all.deb SHA256 size ;-) ...                                                                             [ ok ]
>>> Unpacking source...
>>> Unpacking wps-office-fonts_1.0_all.deb to /var/tmp/portage/media-fonts/wps-office-fonts-1.0/work
>>> Unpacking data.tar.xz to /var/tmp/portage/media-fonts/wps-office-fonts-1.0/work
>>> Source unpacked in /var/tmp/portage/media-fonts/wps-office-fonts-1.0/work
>>> Preparing source in /var/tmp/portage/media-fonts/wps-office-fonts-1.0/work ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/media-fonts/wps-office-fonts-1.0/work ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/media-fonts/wps-office-fonts-1.0/work ...
>>> Source compiled.
 * Skipping make test/check due to ebuild restriction.
>>> Test phase [disabled because of RESTRICT=test]: media-fonts/wps-office-fonts-1.0

>>> Install media-fonts/wps-office-fonts-1.0 into /var/tmp/portage/media-fonts/wps-office-fonts-1.0/image/
>>> Completed installing media-fonts/wps-office-fonts-1.0 into /var/tmp/portage/media-fonts/wps-office-fonts-1.0/image/

du: cannot access '/var/tmp/portage/media-fonts/wps-office-fonts-1.0/work': No such file or directory
 * Final size of build directory: 165452 KiB (161.5 MiB)
 * Final size of installed tree:  165452 KiB (161.5 MiB)


>>> Installing (1 of 1) media-fonts/wps-office-fonts-1.0::gentoo-zh
 * Cleaning up font directories ...                                                                                             [ ok ]
 * Updating global fontcache ...                                                                                                [ ok ]
 * Updating global fontcache ...                                                                                                [ ok ]
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.

 * GNU info directory index is up-to-date.
现在开wps还是报缺少字体

**Comment by tlze** [comment]
字体要自己安装，搜“wps缺少字体”就有方案。
版权问题，wps官方没自带这些字体。

**Comment by Universebenzene** [comment]
@hahsbdb 去找一台Win的电脑把字体拷出来装上罢

**Comment by mintiandeniwo** [comment]
wps-office-fonts这个包没用???

**Comment by mintiandeniwo** [comment]
在wps无法启用ibus输入法...............不会是qt4吧

**Comment by Universebenzene** [comment]
> wps-office-fonts这个包没用???

这个包只包括了一堆有授权的方正字体，那些Simsun，KaiTi，Times New Roman，Wingdings之类的东西都得自己去Win里面拿

**Comment by mintiandeniwo** [comment]
ibus输入法和 wps帐号登录无法启用 .
dev-qt/qtgui开了ibus , ibus也开了gtk gtk2 ,只有wps 上ibus没反映
wps帐号登录不了 点 "未登录"  "点击登录" "云文档" "设置-设置" "设置-皮肤和外观"   或者
"设置-关于wps" 会导致wps直接闪退关闭

**Comment by tlze** [comment]
不能登录这个问题我也一样，还以为wps没开放呢！
在console运行wps点登录也没有任何的信息，想当然以为这个登录是没用的。
只能指望牛人直接反映给kingsoft。
输入法用fcitx-rime试试，我这没问题。

**Comment by Universebenzene** [comment]
WPS的问题太过因人而异了……Arch这里打的包我刚试过可以登录，但AUR评论里总有人说登不了，Gentoo上我还没试……另外就是Gentoo的wpspdf打开没一会就闪退，Arch竟然没有这个问题……这包打得差在哪了呢……
顺便我也是fcitx党，ibus确实不了解……

**Comment by mintiandeniwo** [comment]
基于arch和基于debian的没遇到什么wps的问题,但是gentoo我这炸了

**Comment by mintiandeniwo** [comment]
Gentoo的wpspdf点"新建"也是直接闪退

**Comment by wgjak47** [comment]
@hahsbdb 应该是没有加可执行权限
