### ISSUE TITLE
Linux QQ reborn!

### ISSUE THREAD

**Issue by xen0n** [gentoo-zh/overlay#539]
https://im.qq.com/linuxqq/download.html

**Comment by xen0n** [comment]
NOTE: It's linked with GTK 2, seems to be resurrected from a previous version made for Loongson back in 2009. Things are partially brought up-to-date, though.

**Comment by xen0n** [comment]
I'm going home and ebuild will be up some 2 hours later ;-)

**Comment by wgjak47** [comment]
@seewpx why you guys so interested in qq Linux (
