### ISSUE TITLE
能添加百度网盘么？

### ISSUE THREAD

**Issue by vastchen** [gentoo-zh/overlay#542]
百度网盘出linux版也出了有一段时间了刚刚更新完成eix baidu没看到有，是有别名还是没人写这个ebuild?

**Comment by wgjak47** [comment]
@vastchen 百度的应用比较危险...现在没有打包

**Comment by Universebenzene** [comment]
我在自建的overlay里有写，顺便还打了baidupcs，不过写得差没脸拿出手😷

**Comment by microcai** [comment]
@Universebenzene 勇敢点, 怕啥. 没人嘲笑你. 反而是藏着掖着的人才要被耻笑不贡献呢

**Comment by Universebenzene** [comment]
还是看看大佬们对百度应用的态度罢，毕竟很多菊苣都比较注重安全排斥BAT系的东西……我自用的overlay就在github上（不过我还没试过提pr……回头学学😷

**Comment by microcai** [comment]
@Universebenzene 用户可以不用, 但是你得有.

**Comment by tolbkni** [comment]
介意的不安装就行，想用的可以用

**Comment by vastchen** [comment]
ebuild 应该不会对系统有啥危险吧。用户可以选择安装也可以不安装 ebuild 应该不会太难，我就想着这里有没有问了一下，想建overly 参考腾讯QQ的ebuild

**Comment by Universebenzene** [comment]
提pr了 #543 ，有官方的百度盘还有baidupcs-go……菊苣们可以审查一下😷
