### ISSUE TITLE
libime无法编译成功

### ISSUE THREAD

**Issue by 0x1un** [gentoo-zh/overlay#547]
你们好，维护者。

我在安装完基本系统与i3wm后，再安装fcitx5中文输入法。这一切都很顺利，但唯独在编译安装fcitx5-chinese-addons的时候，libime编译不过。

我折腾这个问题很久，直到我手动去libime仓库拉取并编译，结果是非常顺利的成功了。但是在emerge下安装就会出错，为了能够让emerge管理这些包，我把在~/目录下编译过的libime复制到了portage临时编译目录里，再执行emerge, 成功了。

当我手动去到portage临时编译目录下编译也是不会成功的，报错内容相同！
然而到其他目录(~/)就可以编译成功，我正在学习ebuild构建文件的编写，还不能提交pr。

但这是个问题，我觉得有必要解决，并且认为这不是上游libime的问题。

具体的报错如下面的链接，如果不是用的以上的办法解决，我可能永远也安装不了。

[#2](https://github.com/fcitx/libime/issues/2)

感谢你们的维护 ^_^

**Comment by microcai** [comment]
@0x1un libime-9999 才相当于是 拉仓库编译的版本.

**Comment by 0x1un** [comment]
> @0x1un libime-9999 才相当于是 拉仓库编译的版本.

感谢回复，我在添加gentoo-zh后，直接emerge app-i18n/libime时是会报这个错的，应该不是依赖问题，重试过无数次，最后还是在编译好后copy安装完成的。。
