### ISSUE TITLE
baidunetdisk的linux客户端升级了，emerge下载出错

### ISSUE THREAD

**Issue by AmberisMyShiba** [gentoo-zh/overlay#552]
如题。想尝试修改ebuild并提交request，结果失败。我再研究一下，希望能给这个项目贡献一点微薄之力。

**Comment by Universebenzene** [comment]
其实百度盘升级我老早就提了pr了，只是大概gentoo-zh的菊苣们对BAT系的软件深恶痛绝，所以我那个pr根本没人愿意理（感觉菊苣们不拒我的pr已经是很给面子了😷）

如果想用的话可以考虑加我自己的overlay，就在github上。当然我也是刚学ebuild没多久的萌新，大概会被嫌弃就是😞

**Comment by tolbkni** [comment]
See #546
