### ISSUE TITLE
wps安装问题

### ISSUE THREAD

**Issue by jackycheng86** [gentoo-zh/overlay#555]
Downloading 'http://kdl.cc.ksosoft.com/wps-community/download/8865/wps-office_11.1.0.8865_amd64.deb'
--2020-01-11 15:08:39--  http://kdl.cc.ksosoft.com/wps-community/download/8865/wps-office_11.1.0.8865_amd64.deb
Resolving kdl.cc.ksosoft.com... failed: Name or service not known.
wget: unable to resolve host address ‘kdl.cc.ksosoft.com’
!!! Couldn't download 'wps-office_11.1.0.8865_amd64.deb'. Aborting.
 * Fetch failed for 'app-office/wps-office-11.1.0.8865', Log file:
 *  '/var/tmp/portage/app-office/wps-office-11.1.0.8865/temp/build.log'

>>> Failed to emerge app-office/wps-office-11.1.0.8865, Log file:

>>>  '/var/tmp/portage/app-office/wps-office-11.1.0.8865/temp/build.log'

**Comment by wgjak47** [comment]
@jackycheng86 应该是WPS升级了，我明天更新一下版本就OK了

**Comment by Universebenzene** [comment]
gentoo-zh 这里的SRC_URI还在用wps-community.org这个旧网站给的地址，然而wps community网站已经彻底下线了，这个SRC_URI也有好一段时间不能用了。（好像应该有几个月了罢？大概这段时间一下没人从gentoo-zh里装wps？）
换链接是一方面，新版还有一个事是国际版和国内版搞出区别来了，国际版把账号登录、团队、云文档什么的都撤掉了，连中文支持也没有了。国内版还留着。我在Arch那边打包的时候搞了个拆包策略，gentoo-zh这边的话是用国内版还是国际版大概还得菊苣们斟酌。
再有，Arch那边有些KDE菊苣们表示wps自带的mime会搞出问题，所以我在Arch那也专门拆了个包出来，Gentoo不知道有没有遇到这个的。如果有遇到的要不要考虑搞个mime的USE啥的？

（码完字突然想起菊苣们对国产软件都挺讨厌的，估计我说这么多菊苣们也不会理……不然我还是去我的overlay上另起炉灶一个？

**Comment by microcai** [comment]
@Universebenzene 快点啊，啥问题呢

**Comment by Universebenzene** [comment]
@microcai 呃……蔡博士是从群里用bot回的消息罢，我是直接在github上把刚刚那个回复编辑了，没写新回复，可能bot只更新新回复不更新修改回复……

**Comment by jackycheng86** [comment]
那大佬们，什么时候可以修复呢？或者有没有其他解决办法呢？

**Comment by wgjak47** [comment]
@jackycheng86 可以先用官方的WPS

**Comment by jackycheng86** [comment]
> @jackycheng86 可以先用官方的WPS

官方是deb的包，怎么安装呢？没有试过，能指导一下吗 @wgjak47

**Comment by wgjak47** [comment]
@jackycheng86 Gentoo官方是有打包app-office/wps-office的，直接emerge app-office/wps-office::gentoo即可

**Comment by jackycheng86** [comment]
好的，我明白了，我还以为你说的官方是去官方网站下载的deb包的，谢谢！ @wgjak47

**Comment by Universebenzene** [comment]
由于新版WPS的国际版把中文支持给去了，官方portage里的只有国际版，于是我自己尝试打了一个，在我自己的[overlay](https://github.com/Universebenzene/benzene-overlay/tree/master/app-office/wps-office)里。不过ebuild写得非常ugly，如果有菊苣抽空帮忙给点修改意见也好……😷
