### ISSUE TITLE
USE xcb已经被修改成X了，但是gentoo-zh还有部分依赖这个

### ISSUE THREAD

**Issue by liangyongxiang** [gentoo-zh/overlay#561]
例如 dev-qt/qtgui:5[libinput,xcb]

**Comment by liangyongxiang** [comment]
这是相关的commit：https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=6064fc3aaab4133dd4b368910e8ae94b0d946e54

**Comment by wgjak47** [comment]
问题在于stable版本并没有更改...
