### ISSUE TITLE
Ebuild fails because of missing patch files

### ISSUE THREAD

**Issue by janlam7** [gentoo-zh/overlay#569]
https://github.com/microcai/gentoo-zh/blob/eed23113f3bb3e7cff12c8e5c99a9b8e504d9960/app-misc/nixnote/nixnote-2.1.5.ebuild#L52-L53

The above files seem to be missing from the gentoo-zh overlay, which causes  the emerge to fail.
Should I pick these up from somewhere else ?

**Comment by demonacle** [comment]
Hi, Having the same issue - did you get a resolution?

**Comment by demonacle** [comment]
Try with this overlay instead:
layman -o https://raw.githubusercontent.com/bbugyi200/portage-overlay/master/repository.xml -f -a bbugyi200

**Comment by tlze** [comment]
> Try with this overlay instead:
> layman -o https://raw.githubusercontent.com/bbugyi200/portage-overlay/master/repository.xml -f -a bbugyi200

I copied those two files. thx
