### ISSUE TITLE
app-i18n/cldr-emoji-annotation-36.12.120191002-r0 fatal: not a valid SHA1

### ISSUE THREAD

**Issue by ghost** [gentoo-zh/overlay#580]
~ ❯ sudo cat /var/tmp/portage/app-i18n/cldr-emoji-annotation-36.12.120191002-r0/temp/build.log                                                                                        10:39:48 AM
Password:
 * Package:    app-i18n/cldr-emoji-annotation-36.12.120191002-r0
 * Repository: gentoo-zh
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
 * Repository id: fujiwarat_cldr-emoji-annotation.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_FUJIWARAT_CLDR_EMOJI_ANNOTATION
 *   EGIT_OVERRIDE_BRANCH_FUJIWARAT_CLDR_EMOJI_ANNOTATION
 *   EGIT_OVERRIDE_COMMIT_FUJIWARAT_CLDR_EMOJI_ANNOTATION
 *   EGIT_OVERRIDE_COMMIT_DATE_FUJIWARAT_CLDR_EMOJI_ANNOTATION
 *
 * Fetching https://github.com/fujiwarat/cldr-emoji-annotation.git ...
git fetch https://github.com/fujiwarat/cldr-emoji-annotation.git +HEAD:refs/git-r3/HEAD
fatal: Needed a single revision
git update-ref --no-deref refs/git-r3/app-i18n/cldr-emoji-annotation/0/__main__ 36.12.120191002_0
fatal: 36.12.120191002_0: not a valid SHA1
 * ERROR: app-i18n/cldr-emoji-annotation-36.12.120191002-r0::gentoo-zh failed (unpack phase):
 *   Referencing 36.12.120191002_0 failed (wrong ref?).
 *
 * Call stack:
 *     ebuild.sh, line  125:  Called src_unpack
 *   environment, line 1052:  Called git-r3_src_unpack
 *   environment, line 1002:  Called git-r3_src_fetch
 *   environment, line  996:  Called git-r3_fetch
 *   environment, line  909:  Called die
 * The specific snippet of code:
 *                   die "Referencing ${remote_ref} failed (wrong ref?).";
 *
 * If you need support, post the output of `emerge --info '=app-i18n/cldr-emoji-annotation-36.12.120191002-r0::gentoo-zh'`,
 * the complete build log and the output of `emerge -pqv '=app-i18n/cldr-emoji-annotation-36.12.120191002-r0::gentoo-zh'`.
 * The complete build log is located at '/var/tmp/portage/app-i18n/cldr-emoji-annotation-36.12.120191002-r0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-i18n/cldr-emoji-annotation-36.12.120191002-r0/temp/environment'.
 * Working directory: '/var/tmp/portage/app-i18n/cldr-emoji-annotation-36.12.120191002-r0/work'
 * S: '/var/tmp/portage/app-i18n/cldr-emoji-annotation-36.12.120191002-r0/work/cldr-emoji-annotation-36.12.120191002'

**Comment by ghost** [comment]
@wgjak47

**Comment by wgjak47** [comment]
The author delete all tag in his repo...
Maybe I need to use commit hash instead.

**Comment by ghost** [comment]
> The author delete all tag in his repo...
> Maybe I need to use commit hash instead.



> The author delete all tag in his repo...
> Maybe I need to use commit hash instead.

Thank You!

**Comment by wgjak47** [comment]
You can try it again.
