### ISSUE TITLE
可以添加一个腾讯视频的ebuild么？

### ISSUE THREAD

**Issue by vastchen** [gentoo-zh/overlay#581]
linux下本身娱乐比较少腾讯视频出了linux版可以添加下https://v.qq.com/download.html#linux 腾讯视频的ebuild麽？

**Comment by microcai** [comment]
@vastchen 居然有 linux 版本了？

**Comment by vastchen** [comment]
> 
> 
> @vastchen 居然有 linux 版本了？

有了19年底出的  2019.12.27

**Comment by tlze** [comment]
添加了一个非常简陋的版本，本地测试运行正常，感觉就是包装了个GG浏览器。
我没有测试依赖库等，有问题再反馈吧。
