### ISSUE TITLE
app-office/wps-office manifest changed

### ISSUE THREAD

**Issue by lykling** [gentoo-zh/overlay#596]
package `wps-office_11.1.0.9505_amd64.deb` of `app-office/wps-office` check failed

+ sha512sum of ebuild: `d137d32c0b91d1d668ae552c88faac59831ad0cb0db4f0cab2f46e4fb90b3c0f6df367678aa980923b8d29803a2aea783ffe3b7ed4c69d8589c961f773edc0f1`
+ sha512sum of downloaded: `c54f6842c1169c7a4d9dd374b7959207306c723158d42110934fe1b4d3d02026cb11bf8f86cf9f304f3d24dfbce39094ad65ba9923a63ba4adff773ae09238fb`

seems that the official website have changed the original deb to another one

**Comment by wgjak47** [comment]
you can use gentoo officially provide instead.

**Comment by tlze** [comment]
fixed, thanks
