### ISSUE TITLE
Failed to emerge app-i18n/fcitx5-20200513

### ISSUE THREAD

**Issue by ghost** [gentoo-zh/overlay#598]
[/var/tmp/portage/app-i18n/fcitx5-20200513/work/fcitx5-20200513_build/CMakeFiles/CMakeOutput.log](http://fars.ee/h7I2)

[/var/tmp/portage/app-i18n/fcitx5-20200513/temp/build.log](http://fars.ee/aiXx)

[emerge --info '=app-i18n/fcitx5-20200513::gentoo-zh'](http://fars.ee/tcbm)

[ebuild  N    ] app-i18n/fcitx5-20200513  USE="enchant -coverage -doc -presage -systemd -test"

**Comment by liangyongxiang** [comment]
看报错是依赖libevent，你可以试试emerge -av1 libevent 看看能不能编译过。

**Comment by ghost** [comment]
> 看报错是依赖libevent，你可以试试emerge -av1 libevent 看看能不能编译过。

[ebuild   R    ] 谢谢你，虽然这个已安装，emerge -av1 但是加了1重编译就可以了，谢谢

**Comment by liangyongxiang** [comment]
--oneshot, -1
              Emerge as normal, but do not add the packages to the world file for later updating
这个只是不记录到world文件里面,，在所有软件都不依赖libevent的时候可以被clean掉。你在emerge libevent的时候有注意到useflag变化吗？
这个问题还没有解决吧。

**Comment by ghost** [comment]
> --oneshot, -1
> Emerge as normal, but do not add the packages to the world file for later updating
> 这个只是不记录到world文件里面。你在emerge libevent的时候有注意到useflag变化吗？
> 这个问题还没有解决吧。

[ebuild   R    ] dev-libs/libevent-2.1.11:0/2.1-7::gentoo  USE="ssl threads -debug -libressl -static-libs -test" 0 KiB
印象中是没有变化，我删掉重现一下

**Comment by liangyongxiang** [comment]
@wgjak47 @12101111

**Comment by ghost** [comment]
> @wgjak47 @12101111

删掉libevent后fcitx5并不会自动安装libevent，所以编译失败，应该是ebulid中少了这一个依赖，不好意思没关注use变化，目前的dev-libs/libevent USE="ssl threads

**Comment by wgjak47** [comment]
@keke-cute 可以看一下你选择的profile吗？

**Comment by ghost** [comment]
> @keke-cute 可以看一下你选择的profile吗？

 [26]  default/linux/amd64/17.1/no-multilib (stable) package.use 没有设置libevent，应该是profile默认的

**Comment by wgjak47** [comment]
@keke-cute 可以重新试一下...我把依赖补上了。

**Comment by ghost** [comment]
> @keke-cute 可以重新试一下...我把依赖补上了。

谢谢你，可以了
Calculating dependencies... done!
[ebuild  N     ] dev-libs/libevent-2.1.11:0/2.1-7::gentoo  USE="ssl threads -debug -libressl -static-libs -test" 0 KiB
[ebuild   R    ] app-i18n/fcitx5-20200513:5::gentoo-zh  USE="enchant -coverage -doc -presage -systemd -test" 0 KiB
