### ISSUE TITLE
app-i18n/gcin 2.9.0 released

### ISSUE THREAD

**Issue by reppkchen** [gentoo-zh/overlay#602]
2.9.0

- bug fix: gtab 輸入法如果編輯區顯示設定「應用程式編輯區」，則選字詞的視窗位置不對的問題。
- bug fix: 許氏鍵盤下，「阿諛奉承」的「阿」無法輸入
- gtab 輸入法可預選含空白的詞，像 New York
- gcc 10 相容

**Comment by liangyongxiang** [comment]
已经bump, 但仅仅测试编译结果。
