### ISSUE TITLE
无法打开deepin-wechat和deepin-qq，报错

### ISSUE THREAD

**Issue by hongliangsam** [gentoo-zh/overlay#603]
> 当打开deepin-wechat和deepin-qq时报错如下：

`/usr/bin/deepin-wine：行 45: 23588 段错误               WINEPREFIX=$wineprefix WINELOADER=$wineloader WINEDEBUG=$winedebug $wine "$@"`

请问要如何解决？谢谢

**Comment by RevySR** [comment]
The packages is dropped
