### ISSUE TITLE
Typora下载之后校验失败

### ISSUE THREAD

**Issue by ayamir** [gentoo-zh/overlay#624]
!!! Fetched file: typora-20200706-linux-x64.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      90763143
!!! Expected: 88711107

**Comment by slchris** [comment]
可以删除现有的Manifest文件
然后ebuild typora*.ebuild manifest
再安装就可以了

**Comment by tlze** [comment]
fixed #625
