### ISSUE TITLE
app-misc/nixnote-2.1.5-r1 ebuild fails as can't find Hunspell.pro

### ISSUE THREAD

**Issue by russelld00** [gentoo-zh/overlay#634]
Hi 
app-misc/nixnote-2.1.5-r1 fails as it can't find hunspell.pro

full build log is here: 
https://pastebin.pl/view/92d35bb1

ebuild environment is here: 
https://pastebin.pl/view/7685fa88

Adding details on hunspell and emerge info

$ which hunspell
/usr/bin/hunspell

$ ls -lah /usr/bin/hunspell
-rwxr-xr-x 1 root root 116K Jul 17 20:50 /usr/bin/hunspell

$ equery b /usr/bin/hunspell
Searching for /usr/bin/hunspell ... 
app-text/hunspell-1.7.0-r2 (/usr/bin/hunspell)

$ emerge --info:
https://pastebin.pl/view/2d48701c

kind regards

\ - r

**Comment by russelld00** [comment]
hope you can find some time to fix this ebuild,
kind regards
\- r

**Comment by liangyongxiang** [comment]
> 
> 
> hope you can find some time to fix this ebuild,
> kind regards
> - r

I updated it to 2.1.6. Can you help test it

**Comment by russelld00** [comment]
Hi,
emerged perfectly!
ran in Gentoo perfectly!
Thank you !
