### ISSUE TITLE
fcitx5 编译错误

### ISSUE THREAD

**Issue by HougeLangley** [gentoo-zh/overlay#637]
你好，build日志见附件
[build.log](https://github.com/microcai/gentoo-zh/files/5313639/build.log)

**Comment by wgjak47** [comment]
fcitx5新加了wayland support，但是我没有弄成use...我晚点更新一下新版本

**Comment by HougeLangley** [comment]
> fcitx5新加了wayland support，但是我没有弄成use...我晚点更新一下新版本

非常感谢

**Comment by ghost** [comment]
> fcitx5新加了wayland support，但是我没有弄成use...我晚点更新一下新版本

同样的错误

**Comment by wgjak47** [comment]
应该已经修好了

**Comment by ghost** [comment]
> 应该已经修好了

可以了，謝謝
