### ISSUE TITLE
Failed to build app-i18n/fcitx5-chinese-addons-20200513

### ISSUE THREAD

**Issue by SaltyKitkat** [gentoo-zh/overlay#638]
build log is attached here.
p.s. The fcitx5 version I installed is fcitx5-999999999, because the ~amd64 version build failed (#637 ).
[build.log](https://github.com/microcai/gentoo-zh/files/5323072/build.log)

**Comment by wgjak47** [comment]
should fix with new commit

**Comment by SaltyKitkat** [comment]
Fixed with fcitx5-20201002.
Thank you so much!
