### ISSUE TITLE
app-i18n/libime ninja: error: manifest 'build.ninja' still dirty after 100 tries

### ISSUE THREAD

**Issue by ghost** [gentoo-zh/overlay#644]
[build.log](http://sprunge.us/NQrrlP)

**Comment by liangyongxiang** [comment]
https://github.com/ninja-build/ninja/issues/1599#issuecomment-617411613

**Comment by HougeLangley** [comment]
`ninja: error: manifest 'build.ninja' still dirty after 100 tries`

这里可以记一笔，将来可以帮助再次搜索到这里的朋友。如果你找不到是哪个包导致的时间戳不对劲，最好的方法就是 empty tree
