### ISSUE TITLE
sys-apps/uksmstat的EGIT_GIT_URI指向的仓库已经不存在了。

### ISSUE THREAD

**Issue by liangyongxiang** [gentoo-zh/overlay#660]
![image](https://user-images.githubusercontent.com/8002634/102958415-c238d180-4517-11eb-9753-f892aec6622a.png)

https://github.com/pfactum/uksmstat.git

**Comment by liangyongxiang** [comment]
@vowstar

**Comment by vowstar** [comment]
@pfactum
Hi dear Post-factum, 
we found that this project (https://github.com/pfactum/uksmstat.git) has disappeared. Has this project stopped maintenance?

**Comment by pfactum** [comment]
Yes, it is not published any more for quite some time already.

**Comment by microcai** [comment]
这个是 permission 问题。删了 egit-src 文件夹，修正下权限。

**Comment by liangyongxiang** [comment]
@microcai 上面有回复，的确是不存在了🙈

**Comment by liangyongxiang** [comment]
所以这个包需要drop吗？
