### ISSUE TITLE
gentoo clean py2.7 and some error in qa-reports

### ISSUE THREAD

**Issue by liangyongxiang** [gentoo-zh/overlay#699]
https://qa-reports.gentoo.org/output/repos/gentoo-zh.html

Related packages:

- [x] app-crypt/yubikey-piv-manager
- [x] app-emulation/crossover-bin
- [x] app-misc/geeknote
- [x] app-misc/icdiff
- [x] dev-db/pgcli
- [x] dev-python/notify2
- [x] dev-python/pgspecial
- [x] dev-util/be
- [x] media-plugins/python-mmkeys
- [x] net-proxy/shadowsocks
- [x] net-proxy/wallproxy-plus
- [x] x11-libs/bamf

**Comment by RevySR** [comment]
- [x] app-crypt/yubikey-piv-manager

https://github.com/Yubico/yubikey-piv-manager

The project is archived & it has alternatives

#702 Remove it

```bash
$ emerge -S yubikey                                                                                                                                                                           
[ Results for search key : yubikey ]                                                                                                                                                          Searching...

*  app-crypt/yubico-piv-tool                                                                                                                                                                        Latest version available: 1.4.2
      Latest version installed: [ Not Installed ]                                                                                                                                                   Size of files: 500 KiB
      Homepage:      https://developers.yubico.com/yubico-piv-tool/                                                                                                                                 Description:   The Yubico PIV Tool allows you to configure a PIV-enabled YubiKey through a command line interface.
      License:       GPL-3                                                                                                                                                                    
*  app-crypt/yubikey-manager                                                                                                                                                                        Latest version available: 3.1.1-r1
      Latest version installed: [ Not Installed ]                                                                                                                                                   Size of files: 114 KiB
      Homepage:      https://developers.yubico.com/yubikey-manager/                                                                                                                                 Description:   Python library and command line tool for configuring a YubiKey
      License:       BSD-2
```

**Comment by RevySR** [comment]
- [x] dev-python/notify2

https://bitbucket.org/takluyver/pynotify2

The project is deprecated. & The software hasn't depended by FeelUOwn now

- [x] dev-util/be

The software hasn't depended by FeelUOwn now

#703 Remove them

**Comment by RevySR** [comment]
- [x] app-misc/icdiff

https://github.com/gentoo/gentoo/blob/master/app-misc/icdiff/icdiff-1.9.5.ebuild

gentoo has provided

#704 Remove it

**Comment by RevySR** [comment]
- [x] dev-python/pgspecial

https://github.com/gentoo/gentoo/blob/master/dev-python/pgspecial/pgspecial-1.11.10.ebuild

gentoo has provided

#705 Remove it

**Comment by RevySR** [comment]
- [x] dev-db/pgcli

https://github.com/gentoo/gentoo/blob/master/dev-db/pgcli/pgcli-3.1.0.ebuild

gentoo has provided

#706 Remove it

**Comment by RevySR** [comment]
- [x] x11-libs/bamf

https://github.com/zhtengw/deepin-overlay/blob/master/x11-libs/bamf/bamf-0.5.4-r1.ebuild

It belongs deepin. Please visit https://github.com/zhtengw/deepin-overlay

#707 Remove it

**Comment by RevySR** [comment]
- [x] media-plugins/python-mmkeys

The package isn't depended by other packages. So remove it.

```bash
$ equery d python-mmkeys
 * These packages depend on python-mmkeys:
```

#708 Remove it

**Comment by RevySR** [comment]
- [x] app-emulation/crossover-bin
- [x] app-misc/geeknote
- [x] net-proxy/wallproxy-plus

#709 Remove them
