### ISSUE TITLE
net-misc/sunlogin-personal: The suffix of the file is missing

### ISSUE THREAD

**Issue by ardinzh** [gentoo-zh/overlay#716]
sunlogin-personal-10.0.2.24779_beta
这个文件的后缀名 .ebuild 掉了，请补上．

**Comment by liangyongxiang** [comment]
@ardinzh 你看错仓库了吧？没有这个package

**Comment by Universebenzene** [comment]
这是向日葵？好像官方收录的overlay里就我的overlay打了罢，而且也不叫这名啊。这是要向哪里的overlay反馈问题呃

**Comment by ardinzh** [comment]
哟，更新了就这个了呢。
是大家都不用它了么？
撤了吧。

**Comment by Universebenzene** [comment]
（完全不知道发生了什么

**Comment by ardinzh** [comment]
> （完全不知道发生了什么

已经跟到你那边去啦。。。
