### ISSUE TITLE
gentoo-zh duplicate packages

### ISSUE THREAD

**Issue by liangyongxiang** [gentoo-zh/overlay#746]
|                                            package-name                                             |gentoo-zh versions |    gentoo versions     |                              gentoo maintainer                               |
|-----------------------------------------------------------------------------------------------------|-------------------|------------------------|------------------------------------------------------------------------------|
|[dev-libs/granite](https://packages.gentoo.org/packages/dev-libs/granite)                            |5.2.1              |5.2.5-r1 \| 5.5.0        |xgqt@protonmail.com proxy-maint@gentoo.org                                    |
|[dev-util/global](https://packages.gentoo.org/packages/dev-util/global)                              |6.3.4              |6.6.4                   |naota@gentoo.org arfrever.fta@gmail.com                                       |
|[sys-fs/yaffs2utils](https://packages.gentoo.org/packages/sys-fs/yaffs2utils)                        |0.3.0              |0.2.9                   |embedded@gentoo.org                                                           |
|[virtual/linux-sources](https://packages.gentoo.org/packages/virtual/linux-sources)                  |1                  |3-r5                    |blueness@gentoo.org kernel@gentoo.org                                         |

更新：
- app-office/wps-office: 和main-tree是不同的版本，应该保留。
- media-libs/libuninameslist: add libuninameslist that will be needed by fontforge，应该保留和更新
- sys-fs/jmtpfs 在main-tree没有maintainer，所以先保留

**Comment by liangyongxiang** [comment]
https://gist.github.com/liangyongxiang/445ea6a5a564276e2939cfc0751e1278
写了一个简单的脚本，用来列出所有和main tree重复的包。

**Comment by liangyongxiang** [comment]
有个bug没处理：
``` shell
~ equery m net-misc/you-get

!!! Package net-misc/you-get-9999 is missing metadata.xml
```

**Comment by tlze** [comment]
我只有wps-office在用，这个还是保留着（可以存档状态）。记忆中wps在官方仓库进进出出好几回了，不知那天起来就没了。

**Comment by liangyongxiang** [comment]
@tlze gentoo-zh的wps-office和main tree上的还有一个不同，gentoo-zh里是国内版的。所以我觉得是应该保留。

**Comment by liangyongxiang** [comment]
app-i18n/librime : https://github.com/microcai/gentoo-zh/pull/748

**Comment by liangyongxiang** [comment]
live包保持现状：
- app-i18n/ibus-rime
- app-i18n/man-pages-zh_CN
- media-gfx/sane-backends
- net-misc/you-get
- sci-libs/libticables2
- sci-libs/libticalcs2
- sci-libs/libticonv
- sci-libs/libtifiles2
- sys-fs/f2fs-tools
- sys-libs/libixp
- x11-plugins/vicious

**Comment by RevySR** [comment]
#747 #748 #749 #750 #751 #752 #753 已删除

**Comment by RevySR** [comment]
#755 #757 #758 #759 #760 #761 已删除

**Comment by dlan17** [comment]
> live包保持现状：
> 
>     * app-i18n/ibus-rime
这个我也想删掉，但是需要先bump
看了下ibus-rime发布了1.5.0
app-i18n/librime发布了1.7.3

或者有自愿者帮忙bump吗？可以去github提个PR ; - )

**Comment by liangyongxiang** [comment]
> > live包保持现状：
> > ```
> > * app-i18n/ibus-rime
> > ```
> 
> 这个我也想删掉，但是需要先bump
> 看了下ibus-rime发布了1.5.0
> app-i18n/librime发布了1.7.3
> 
> 或者有自愿者帮忙bump吗？可以去github提个PR ; - )

我来试一下吧

**Comment by liangyongxiang** [comment]
ibus-rime已经bump了

**Comment by liangyongxiang** [comment]
- app-arch/unzip 已经删除
- app-i18n/ibus-handwrite: 等菜博更新
- dev-cpp/ETL: gentoo-zh里更新
- media-libs/libuninameslist: gentoo-zh里更新
- media-plugins/gst-plugins-meta: 已经删除
- dev-python/pydantic: gentoo-zh里更新

**Comment by liangyongxiang** [comment]
没有需要drop的包了。
