### ISSUE TITLE
media-libs/libuninameslist 需要保留吗？

### ISSUE THREAD

**Issue by liangyongxiang** [gentoo-zh/overlay#766]
现在gentoo-zh里，media-libs/libuninameslist里是20190701，main tree里是20091231。
但是gentoo-zh里从github下载，而main tree里面是从sourceforge下载。

@tlze

**Comment by tlze** [comment]
超过main tree版本的一般是有人依赖或需要的（如测试的目的），应当作存档留着，以免“破坏”别人的系统。
建议这样的包不必花时间去做更新维护，以后再作检视删除。

**Comment by tlze** [comment]
有点忙，老眼花了。（这条消息没用）
我编辑了几次信息，原因是不想系统发太多邮件，影响其它人。
回了上条消息后，看邮件以为我看错了版本日期，直接邮件回了条消息“说看错了”。
然后被我编辑掉了，应该没看错。
总之这条comment是没用的，不用看。

**Comment by liangyongxiang** [comment]
> 应当作存档留着

现在是gentoo-zh里是旧版。唯一的优点应该是从github下载而不是sourceforge下载，被屏蔽的概率更低。所以我不知道是否要继续保留。

**Comment by tlze** [comment]
[-P-] [  ] media-libs/libuninameslist-20091231-r1:0
[--O] [  ] media-libs/libuninameslist-20140731:0
[--O] [  ] media-libs/libuninameslist-20190701:0

这里的才是新的。

**Comment by liangyongxiang** [comment]
是的。我看错了，我把2009堪称2019了

> 
> [-P-] [ ] media-libs/libuninameslist-20091231-r1:0 [--O] [ ] media-libs/libuninameslist-20140731:0 [--O] [ ] media-libs/libuninameslist-20190701:0 这里的才是新的。
> […](#)
> On Mon, Mar 1, 2021 at 11:50 AM 梁永祥 ***@***.***> wrote: 应当作存档留着 现在是gentoo-zh里是旧版。唯一的优点应该是从github下载而不是sourceforge下载，被屏蔽的概率更低。所以我不知道是否要继续保留。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
