### ISSUE TITLE
dev-libs/tdlib-9999 build failed

### ISSUE THREAD

**Issue by ghost** [gentoo-zh/overlay#785]
>>> Working in BUILD_DIR: "/var/tmp/portage/dev-libs/tdlib-9999/work/td/build"
ninja -v -j13 -l0
ninja: error: '../td/generate/auto/tlo/mtproto_api.tlo', needed by 'td/generate/CMakeFiles/tl_generate_common', missing and no known rule to make it

[full log](https://fars.ee/Dfhd)

[emrege --info](https://fars.ee/i2cN)

**Comment by liangyongxiang** [comment]
@locez
