### ISSUE TITLE
 games.eclass could not be found by inherit( )

### ISSUE THREAD

**Issue by ethanzhang9** [gentoo-zh/overlay#897]
After adding Gentoo zh source to the repository, using emerge -s will cause the problem that games.eclass cannot be found. What is the reason?

The error is as follows:

ERROR: games-board/othe1l0-0.2.0: :gentoo-zh failed ( depend phase):
games.eclass could not be found by inherit( )
Call stack:
ebuild.sh, line 609: Called source '/home/var /db/ repos/gentoo-zh/games-board/othello/othe1lo-0.2
.0.ebuild'
othello-0.2.0. ebuild, Line 4: Called inherit ' games'
ebuild.sh, line 290: Called die 
The specific snippet of code:
[ -Z ${location} ]] && die "${1}.eclass could not be found by inherit( )"
If you need support, post the output of‘ emerge --info '=games- board/othello-0.2.0: :gentoo-zh' ,
the complete build Log and the output of" emerge -PqV . agames -board/othel Lo-0.2.➊:: gentoo- zh '
Working directory; /usr/lb/python3. 8/site-packages'
S: ' /home/var/portage/ tmp/portage/ games -board/othello-0.2.@/work/othello-0.2.0
emerge: search: aux. .get( ' games -board/othello-0.2.0') failed, sktpping

**Comment by bekcpear** [comment]
PR Created https://github.com/microcai/gentoo-zh/pull/898
