### ISSUE TITLE
need mozc for fctix5

### ISSUE THREAD

**Issue by stalkerg** [gentoo-zh/overlay#908]
Subj.

**Comment by liangyongxiang** [comment]
The packaging of mozc is more complicated than that of fcitx5-skk.
And no one is interested in packaging it now.

Are you interested in packing?

**Comment by stalkerg** [comment]
> The packaging of mozc is more complicated than that of fcitx5-skk.

Agree, I have already tried... honestly much easier to make an extra fork, migrate to Meson from Bazel, and tried to support system libs by default. 

> Are you interested in packing?

yes... SKK working but it's much simpler and low productivity than mozc.

**Comment by liangyongxiang** [comment]
Welcome to create PR
