### ISSUE TITLE
Please add netease-cloud-music-gtk as alternative to official one

### ISSUE THREAD

**Issue by ackmangogo** [gentoo-zh/overlay#938]
For people use gtk+ based DE is more friendly.

Project url:
[https://github.com/gmg137/netease-cloud-music-gtk](https://github.com/gmg137/netease-cloud-music-gtk)

A simple ebuild converted from cargo-ebuild here.
[](url)
[netease-cloud-music-gtk-1.2.2.ebuild](https://raw.githubusercontent.com/ackmangogo/init-files/main/netease-cloud-music-gtk-1.2.2.ebuild)

Compiled and works fine.

Thanks

**Comment by wgjak47** [comment]
can try feeluown first or welcome to create PR.
