### ISSUE TITLE
Make repoman happy

### ISSUE THREAD

**Issue by liangyongxiang** [gentoo-zh/overlay#944]
在gentoo-zh下运行 `repoman full -d`，可以看到输出相对多的QA(Quality Assurance)提示。
如果只关心具体某个包，可以cd进去然后运行`repoman full -d`

这是我运行的输出： http://fars.ee/odjC

**Comment by liangyongxiang** [comment]
现在需要更多小伙伴们一起帮忙来修复这些QA小问题。

有兴趣的可以修复然后发pr～

**Comment by liangyongxiang** [comment]
https://github.com/microcai/gentoo-zh/pull/1014
https://github.com/microcai/gentoo-zh/pull/1015
https://github.com/microcai/gentoo-zh/pull/1016
https://github.com/microcai/gentoo-zh/pull/1017

**Comment by liangyongxiang** [comment]
http://fars.ee/cHYj

还剩下2567行

**Comment by liangyongxiang** [comment]
最近的pr绝大部分的是QA相关，懒得一一列出来了～

**Comment by liangyongxiang** [comment]
http://fars.ee/RU6k
1000以下，主要是处理了keyword和depend相关的（一个错误会产生非常多的警告）

**Comment by liangyongxiang** [comment]
https://github.com/microcai/gentoo-zh/pull/1068
https://github.com/microcai/gentoo-zh/pull/1069

**Comment by liangyongxiang** [comment]
repoman大概还有600多行。
http://fars.ee/nFGu
http://fars.ee/0m89

**Comment by liangyongxiang** [comment]
todo:https://github.com/microcai/gentoo-zh/pull/1314

**Comment by Universebenzene** [comment]
今偶然发现一件事

dev-python 下某位菊苣提交的所有py包依赖全部没写 `[${PYTHON_USEDEP}]`

其他涉及python-r1或python-single-r1的包暂时没看

**Comment by liangyongxiang** [comment]
> 今偶然发现一件事
> 
> dev-python 下某位菊苣提交的所有py包依赖全部没写 `[${PYTHON_USEDEP}]`
> 
> 其他涉及python-r1或python-single-r1的包暂时没看

pr一下?

**Comment by Universebenzene** [comment]
@liangyongxiang 有点多……我找机会一个一个慢慢来罢

**Comment by liangyongxiang** [comment]
@Universebenzene

**Comment by liangyongxiang** [comment]
give up

**Comment by Universebenzene** [comment]
@liangyongxiang 咦，才发现，好突然
